= Khoo Yuan Hui - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

= PROJECT: FreeTime

---

== Overview

|===
This Project Portfolio outlines my personal contributions to this team project.
|===

FreeTime is the product of my CS2113T project. In CS2113T, our team of 4 had to morph an existing application (AddressBook 4) into a different application, all the while ensuring the best coding practices and teamwork.

FreeTime is a Time-Planner application. It is primarily aimed at Students. The most unique feature about FreeTime is that it has the ability to quickly display the times when a group of friends are able to meet up. +

The main interaction is through a command-line interface (CLI), but the graphical user interface (GUI) is also available. It is written in Java, and has about 10 kLoC. +

== Summary of contributions
|===
This section is a brief summary of my personal contributions to this team project.
|===

* *Major enhancement*: *Import and Export Command*
** What it does: Allows the user to import and export timetables that are in the .ics format.
** Justification (Import): It is a time consuming process for users to manually add their timeslots one-by-one. The import command makes users' lives so much easier, because adding a full timetable is now reduced to a 1-step process.
** Justification (Export): Having a export feature can allow users to share their personal timetables with their friends.
** Highlights: I learnt to implement a third-party library into an existing product. It also taught me to be meticulous in my coding, as there can be many unforeseen issues with certain implementations of code. For example, I ran into a timezone bug because I focused too much on implementing logic and left out on testing.
** Credits: biweekly third-party library (https://github.com/mangstadt/biweekly)

* *Minor enhancement*: *Save user's timetable across application instances*.
** What it does: Allows the application to save the timetable into the disk automatically. This means that it can remmeber our users' timetables across restarts.

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=alexiscatnip[Link to RepoSense]]

* *Other contributions*:

** Project management:
*** Contributed to releases `v1.1` - `v1.4` (3 releases) on GitHub
** Documentation:
*** Created documentation for import, export command and save timetable feature.
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2113-AY1819S1-W13-1/main/pull/166[#116]
*** Contributed to forum discussions (examples:  https://github.com/nusCS2113-AY1819S1/forum/issues/63[63])
** Tools:
*** Integrated a third party library (biweekly) to the project (https://github.com/CS2113-AY1819S1-W13-1/main/pull/55[#55])


== Contributions to the User Guide

|===
Here are my contributions to the User Guide. I tried to write it so that users could easily understand the commands. I have also included step-by-step instructions for the examples, so that users can get started quickly.
|===

include::../UserGuide.adoc[tag=import]

include::../UserGuide.adoc[tag=export]

== Contributions to the Developer Guide

|===
Here are my contributions to the Developer Guide. I tried to write it to be as informative as possible for Developers who are going to take over my code. They showcase my ability to write technical documentation targeting developers.
|===

include::../DeveloperGuide.adoc[tag=import_export_timetable]


== PROJECT: <some other project>

---

_{Optionally, you may include other projects in your portfolio.}_
