= Tay Ran Tian - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Something Daily

---

== Overview

Something Daily is a desktop task and expenditure tracker application created for NUS SoC students to aid them in their busy student life. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Designed *model component for To-do List*
** What it does: It is the component that holds all to-do list related data of the app in-memory.
** Justification: This component is a core building block of the to-do list in the app.

* *Major enhancement*: Designed *storage component for To-do List*
** What it does: It is the component that reads and writes to-do list data to the hard disk.
** Justification: This component allows user's to-do list data to be stored, hence allowing the user to keep track of his/her task's progress.

* *Major enhancement*: Added *the ability to mark a task as completed/uncompleted*
** What it does: The command allows the user to mark a specific task in the to-do list as completed or uncompleted. The status is then updated accordingly in the UI of the to-do list.
** Justification: This feature is key to a functioning to-do list, where users can keep track of the status of his/her tasks.
** Highlights: This enhancement enables commands like viewing a filtered list based on task's status.

* *Major enhancement*: Added *the ability to view a filtered list of tasks*
** What it does: The command allows the user to view a list of tasks based on task's status.
** Justification: This feature improves the user experience and efficiency as it helps the user in navigating through all of the tasks in the to-do list. Users can now easily separate out uncompleted tasks from completed task.

* *Minor enhancement*: updated application icon and application name to reflect on our product
* *Minor enhancement*: modified console messages in the application to enhance user experience

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Set up team organisation on GitHub
*** Set up and managed GitHub issue tracker and labels
*** Set up and managed milestones on GitHub
*** Managed releases `v1.2` - `v1.3.1` (3 releases) on GitHub

** Documentation:
*** Updated README document to reflect our application
*** Updated the About Us page to reflect our team members
*** Restructured commands listing in section 3 & 5 of the User Guide
*** Updated class diagrams for model and storage components in Developer Guide

** Tools:
*** Set up Travis CI for the team repo
*** Set up Coveralls for the team repo
*** Set up Codacy for the team repo
*** Set up auto-publishing of documentations for the team repo

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=TDLadd]

include::../UserGuide.adoc[tag=TDLedit]

include::../UserGuide.adoc[tag=TDLdelete]

include::../UserGuide.adoc[tag=TDLcomplete]

include::../UserGuide.adoc[tag=TDLuncomplete]

include::../UserGuide.adoc[tag=TDLview]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=completeuncomplete]

include::../DeveloperGuide.adoc[tag=viewtask]
