= Benjamin Chong Zhi Yi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:mainRepoPRURL: https://github.com/CS2113-AY1819S1-W13-1/main/pull
:mainRepoIssueURL: https://github.com/CS2113-AY1819S1-W13-1/main/issue

== PROJECT: FreeTime

---

== Overview


FreeTime(TM) is a security-enabled desktop application that is used for finding mutually available slots between its users. This
available slot will be displayed for the user to choose from, which will be reflected in his timetable using our _FreeTime's_
Graphical User Interface (GUI).

This project portfolio would be introducing you to my team that has developed this product in the span of a semester. In addition to giving you a brief general overview of this application
feature, I would be going in depth into the details on how my own features are implemented. This is to give you a deeper understanding of what contributions that I have done within this project,
and hopefully you would perhaps too be interested in this project of mines.

So sit tight, and let me tell you more about _FreeTime_, and how it will make scheduling meetings easier.

== FreeTime(TM) Introduction
In addition to essential security features such as login and registering, we have a clean, minimalistic landing page that is user-friendly.

Users can import preexisting timetables that are taken from Google Calender or any other calender application that saves their data into the commonly used .ics format. This handy feature allows
quick integration for users coming from other timetable applications that lack _FreeTime_'s feature.

On top of having friends to look at their timetable, users are also grouped with groups according to what they have inputted. This is to easily select friends that are in the same group as you, which then sets the stage to find the mutually free slot among
this particular group of friends.

NOTE: You can be part of multiple groups, or none at all

Using the command `freetime`, you would be presented with a timetable that shows you what are your common free slots are.
Thus you are freed from the pains of finding a common free slot in huge groups.


== Summary of contributions
In this section, I would be briefly telling you about my contributions to this project, and any interesting points that you could find useful.


GIVE THE REASON WHY. USE LONGER SENTENCE BELOW

* *Major enhancement*: Added *the ability to authenticate users* within _FreeTime_
** What it does: Allows the users to have unique access and control to his own timetable
** Justification: To be able to prevent others from editing your own timetable, and to facilitate different privacy levels.
Privacy levels are given to users to have control over what they feel comfortable sharing between strangers and friends.
** Highlights: Implementing the above is not trivial as I had to rewrite how the commands are parsed and executed, which are
then handled in SecurityManager. This is done on top of having to deal with new commands such as login, and restructuring
old command into register. I had to understand and improve on all modules to make them to work together in this new sytem.


* *Minor enhancement*: Used a hashing feature together with a salt to store user's password in json format. This is to improve security by
not storing users' password in plaintext, but encrypted securely.

* https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=bennchong[*Code contributed*]
* link:https://github.com/CS2113-AY1819S1-W13-1/main/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Abennchong[*Pull Requests Made*]

* *Project Overheads*



** Project management:
*** Contributed to releases `v1.1` - `v1.4` (4 releases) on GitHub
*** link:https://github.com/CS2113-AY1819S1-W13-1/main/issues/24[Milestone issue tracker]

** Enhancements to existing features:
*** Updated Storage Module to include AppUsersJson {mainRepoPRURL}/63[#63]
*** Changed AddressBookParser to accommodate Security Implementation {mainRepoPRURL}/153[#153]

** Documentation:
*** Updated Screenshots in User Guide {mainRepoPRURL}/192[#192]

** Community:
*** PRs reviewed (with non-trivial review comments): {mainRepoPRURL}/64[#64], {mainRepoPRURL}/173[#173],
*** Fixed bugs in program {mainRepoPRURL}/75[#75], {mainRepoPRURL}/185[#185], {mainRepoPRURL}/186[#186]


== My User Guide Contributions

A User guide is given to the targeted audience of the application, and usually is written in a step-by-step way to guide
new users to use the application.

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=security]
include::../UserGuide.adoc[tag=securityP2]


== My Developer Guide Contribution

On the other hand, a developer guide is written for technical stakeholders that are interested in the implementation
of the methods, and might be working on extending the project.

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=designSecurity]

include::../DeveloperGuide.adoc[tag=securityImplementation]

