= Benjamin Chong Zhi Yi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FreeTime

---

== Overview


FreeTime is a security-enabled desktop application that is used for finding mutually availble slots between its users. This
available slot will be displayed for the user to choose from, which will be reflected in his timetable using our FreeTime GUI.

This project portfolio would be introducing you to my team that has developed this product in the span of a semester. In addition to giving you a brief general overview of this application 
feature, I would be going indepth into the details on how my own features are implemtented. This is to give you a deeper understanding of what contributions that I have done within this project,
and hopefully you would perhaps also learn something along the way.

So sit tight, and let me tell you more about FreeTime. 

== FreeTime Features
In addition to essential security features such as login and registering, we have a clean, minimalistic landing page that is user-friendly. 

Users can import preexisting timetables that are taken from Google Calander or any other calander application that saves their data into the commonly used .ics format. This handy feature allows
quick integraton for users coming from other timetable applications that do not have our main feature. 

On top of having friends to look at their timetable, Users are also grouped with groups according to what they specify. This is to easily select friends that are in the same group as you, which then sets the stage to find the mutually free slot among 
this particular group of friends.

Using the command `freetime`, you would be presented with a timetable that shows you what are your common free slots are. Thus you are freed from the painful moments of finding a common free slot in huge groups.



== Summary of contributions
In this section, I would be briefly telling you about my contributions to this project, and any interesting points that you could find useful.

* *Major enhancement*: added *the ability to authenticate users*
** What it does: Allows the users to have unique access and control to his own timetable
** Justification: To prevent malicious users to edit other users' timetable, and to introduce different privacy levels. Other users that you are friends with allows you to view their 
timetables and find common slots with them. 
** Highlights: Other than having the ability to add friends, you are now able to add groups since each users are differentiated from each other


* *Minor enhancement*: Used a hashing feature together with a salt to store user's password

* *Project Overheads*

** Project management:
*** Contributed to releases `v1.0` - `v1.4` (4 releases) on GitHub

** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])


== My User Guide Contributions

A User guide is given to the targeted audience of the application, and usually is written in a step-by-step way to guide
new users to use the application.

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=security]


== My Developer Guide Contribution

On the other hand, a developer guide is written for technical stakeholders that are interested in the implementation
of the methods, and might be working on extending the project.

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=designSecurity]

include::../DeveloperGuide.adoc[tag=securityImplementation]

