= Chia Xiang Rong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:site-section: chiaxr
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/CS2113-AY1819S1-T12-1/main

[big]#PROJECT: Event Manager#

== Overview
This document provides a summary of my contributions as a developer of the Event Manager project. It showcases both my proficiency in software engineering and clarity in technical writing.

Event Manager is a cross-platform desktop application that manages events, targeted at the Halls and Residential Colleges of NUS. These residences tend to host many events for their students, and it can be difficult to keep track of events amidst the students' daily lives. Our application aims to consolidate these events and present them in a clear manner, allowing the residents to easily sieve through upcoming events that they are interested in.

Other main features include:

* Authentication
* Registration
* Reminders
* Comments
* Searching & Sorting
* Export of calendar file

The user interacts with the application using a Command Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX. All features can be used by typing commands in the CLI, but the GUI provides important information as well as some ease of use to the user. It is written in Java, and has about 10 kLoC.

This project was developed as part of CS2113T (Software Engineering & Object-Oriented Programming) by a team of 5 students, over a period of 8 weeks.

== Summary of contributions
My contributions to the project are described below.

* *Major enhancement*: Added *the ability to register/unregister for events and view attending events*
** *What it does*:
+
Users can indicate their attendance for events, and view the usernames of other attendees. Events that the user are attending can be filtered out and displayed.

** *Justification*:
+
This feature encourages users to attend events and connect with other users they know who are attending the same event, promoting social engagement in the community. It also provides event coordinators with a rough estimate of the turnout, allowing them to make suitable preparations for the event, e.g. ensuring ample logistics and manpower.

** *Highlights*:
+
This enhancement required an in-depth analysis of design alternatives. The implementation too was moderately difficult as it required modification to the existing storage format.

* *Minor enhancement*:
** Formatting and display of event details in event page, with proper URL encoding (https://github.com/CS2113-AY1819S1-T12-1/main/pull/182[#182])
** Assisted morphing of product to fit context of project

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=chiaxr&sort=displayName&since=2018-09-12&until=2018-10-23&timeframe=day&reverse=false&repoSort=true[RepoSense link]]

* *Other contributions*:

** Project management:
*** Ensure milestones are met and assist teammates in debugging
*** Wrote additional tests for registration features to increase coverage (Pull request https://github.com/CS2113-AY1819S1-T12-1/main/pull/109[#109], https://github.com/CS2113-AY1819S1-T12-1/main/pull/182[#182])
** Documentation:
*** Updated User and Developer Guides to describe new features: https://github.com/CS2113-AY1819S1-T12-1/main/pull/103[#103], https://github.com/CS2113-AY1819S1-T12-1/main/pull/186[#186], https://github.com/CS2113-AY1819S1-T12-1/main/pull/188[#188]
** Community:
*** PRs merged: https://github.com/CS2113-AY1819S1-T12-1/main/pull/90[#90], https://github.com/CS2113-AY1819S1-T12-1/main/pull/97[#97]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=rsvp]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=rsvp]

=== Use Cases
include::../DeveloperGuide.adoc[tag=rsvpUsecase]

include::../DeveloperGuide.adoc[tag=rsvpTestingInstructions]
