= Cheng Jin Ting - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FreeTime

---

== Overview

_FreeTime_ is a desktop application targeted at students who have many projects that require meeting many people at different times.
_FreeTime_ aims to reduce the hassle of find available timeslots in which everyone is mutually available.
This project is part of the deliverables for the following modules offered by the School of Computing in the National University of Singapore: +

*CS2113T - Software Engineering and Object-Oriented Programming* +
*CS2101 - Communication for Computing Professionals* +

The user interacts with it using a Command Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX. It is written in Java, and has about 10 kLoC.

This project portfolio shows my contributions to the project, which includes the learning the Java Programing Language.

== Summary of contributions

* *Major enhancement*: added the concept of *friends* and *the ability to friend/unfriend a user in the database*
** What it does: Invoking the `friend` command will add the selected person to your friend list.
`unfriend` will do the remove an existing friend from the friend list.
** Justification: The idea of the application is to work as a social platform where users can look for other users with similar modules and to coordinate timetables with them.
Before adding a particular user as a friend, the timetables and other personal information about the user will be obscured.
This is to address privacy concerns of users revealing too much information to unknown people.
** Highlights: Implementing this concept and commands required that the main UI to be modified and changes how the logic works fundamentally.
I had to learn how to use JavaFX to manage the different panels to show the friends and users individually.
The implementation too was challenging as it required changes to the main logic of the code and many tests were changed as a result.

* *Minor enhancement*: added a tag command that allows the user to search for persons by module code.
This is to enhance the search feature in the case where there are too many users in the database.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Enhancements to existing features:
*** Designed and updated the existing application icon and title.
** Documentation:
*** Ensured consistency in the UserGuide and DeveloperGuide.

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=tagcommand]

include::../UserGuide.adoc[tag=friendcommand]

include::../UserGuide.adoc[tag=unfriendcommand]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
