= Elston Aw - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: JitHub - Schedule Management System

== Overview
This portfolio is written to document the software engineering process of CS2113T. +

For this software engineering project, I am a developer and code quality control expert, and my responsibilities are to write improvements for the software, and to ensure that the codes are of an excellent standard before allowing major releases of the software.

Our team, CS2113T-W12-1, consists of 5 students, Bao Lin Ruo, Chun Hong Wei, Elston Aw, Lim Jit Wei and Low Jun Wei.
We are a team based in the School of Computing, National University of Singapore.
// about contributions
// showcase ability to produce code
// name whatever we learnt
// 2 sentences

== Project Introduction

JitHub is an application that saves your contacts and helps you schedule meetings through cross-checking the timetable of your group mates.
It is a CLI (Command Line Interface) application with GUI output so that you can have best of the both worlds.
JitHub is a Java application that you can run on any machine with Java Runtime Environment installed.
// condense
// 1-2 liner
//meeting organiser

== Summary of contributions

* *Major enhancement*: added *the ability to suggest smart suggestions and corrections while typing*
** What it does: It gives the users smart suggestions when the users press tab, to suggest them of the full command name and its relevant syntax.
** Justification:  a user can make mistakes in commands and the app should provide a convenient way to rectify them.
// saves time and helps making it convenient etc
** Highlights: write technical skills i acquired like new algorithm etc
** Credits:
*** [https://www.geeksforgeeks.org/trie-insert-and-search/[GeeksforGeeks]] for their explanation on Trie data structure which was heavily used to implement this feature.

* *Minor enhancement*: Added a wrong command suggestion when the user types in a wrong command and presses enter.
** What it does:
** Justification:
** Highlights
** Credits:
*** [https://github.com/trekhleb/javascript-algorithms/tree/master/src/algorithms/string/levenshtein-distance[trekhleb/javascript-algorithms]]
    for their explanation on Levenshtein distance (edit distance)
//elaborate
//justify
//learning points
* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=elstonayx[Code]]


== Contributions to the User Guide
//the following contributions are blan blsh

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=suggestions]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=suggestion]

