= Elston Aw - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: JitHub - Schedule Management System

== Overview
This portfolio is written to document the software engineering process of CS2113T. +

For this software engineering project, I am a developer and code quality control expert, and my responsibilities are to write improvements for the software, and to ensure that the codes are of an excellent standard before allowing major releases of the software.

Our team, CS2113T-W12-1, consists of 5 students, Bao Lin Ruo, Chun Hong Wei, Elston Aw, Lim Jit Wei and Low Jun Wei.
We are a team based in the School of Computing, National University of Singapore.

== Project Introduction

JitHub is an application that saves your contacts and helps you schedule meetings through cross-checking the timetable of your group mates.
It is a CLI (Command Line Interface) application with GUI output so that you can have best of the both worlds.
JitHub is a Java application that you can run on any machine with Java Runtime Environment installed.

== Summary of contributions

* *Major enhancement*: added *the ability to suggest smart suggestions and corrections while typing*
** What it does: It gives the users smart suggestions when the users press tab, to suggest them of the full command name and its relevant syntax.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: geekforgeeks.com for their explanation on Trie data structure which was heavily used to implement this feature.

* *Minor enhancement*: Added a wrong command suggestion when the user types in a wrong command and presses enter.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=suggestions]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=suggestion]

