= Xin Shenzi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Something Daily

---

== Overview

Something Daily is a desktop address book application used for teaching Software
Engineering principles. The user interacts with it using a CLI, and it has a GUI
created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the check command for Expenditure Tracker*
** What it does: allows the user to check how much money they have spent in a specific period.
** Justification: This feature improves the product significantly because if a user want to know how much money they have spent in a period, they can easily get the value.

* *Major enhancement*: added *a chart to show the expenditure*
** What it does: allows the user to see where and how much they have spent when they want to use the check command.
** Justification: This feature improves the product significantly because users can see their each expense in a period directly.
** Highlights: This enhancement will appear a new window to show the chart.
** Credits: This feature needs another library *jfreechart* to draw the chart.

* *Major enhancement*: added *the ability to delete an expenditure*
** What it does: allows the user to delete an expenditure by index.
** Justification: This feature improves the product significantly because users may add a wrong expenditure.

* *Major enhancement*: added *the ability to edit an expenditure*
** What it does: allows the user to edit an expenditure by index.
** Justification: This feature improves the product significantly because users may want to change some parts of an expenditure.

* *Minor enhancement*: change GUI for expenditure tracker part
* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test
code]] _{give links to collated code files}_

* *Other contributions*:

** Community:
*** PRs reviewed (with review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
** Tools:
*** Integrated a third party library (jFreeChart) to the project

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability
to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=ETcheck]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my
ability to write technical documentation and the technical depth of my contributions
to the project._
|===

include::../DeveloperGuide.adoc[tag=checkexpenditure]



== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
