= Tan Yuan Cai - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Trajectory

---

== Overview

Trajectory is a lightweight management system for those who need a no-frills solution for managing students, modules, grades, classes and notes. It is built for users who prefer typing (CLI) over GUI interaction and has a GUI created with JavaFX.

== Summary of contributions

* *Code contributed*: https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=harriuscai
* *Main feature implemented*: added *the ability to manage modules-related matters in Trajectory*
** What it does: allows the user to create and manage modules in Trajectory. The user is also able to enrol students into the modules to keep track of the students taking the module.
** Justification: This feature is a key component in any learning management system such as Trajectory because the users **need** to keep track of their various modules.
** Highlights: High cohesiveness with the other features in Trajectory because `Module` is an integral part of any learning management system.

* *Minor enhancement*: updated the main parser to allow multi-word commands without breaking existing commands.
* *Minor enhancement*: implemented a MVC-like pattern for interaction between classes in the `Model` and `Storage` layers for the team to adopt.

* *Other contributions*:

** Documentation:
*** Did cosmetic tweaks to enable 3 levels of depth in the User Guide: https://github.com/CS2113-AY1819S1-T16-1/main/pull/36[#36]
*** Rearranged the `Gradebook` and `Class` sections of the use cases in the Developer Guide to be consistent with the user stories. https://github.com/CS2113-AY1819S1-T16-1/main/pull/36[#36]
*** Updated some project-specific sections in the Developer Guide and User Guide. https://github.com/CS2113-AY1819S1-T16-1/main/pull/36[#36]

** Community:
*** Reviewed the majority of the PRs opened by my team members

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=modulemanagement]

include::../UserGuide.adoc[tag=modulemanagementsummary]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=modulebiddingimplementation]

include::../DeveloperGuide.adoc[tag=moduleusecases]

include::../DeveloperGuide.adoc[tag=modulemanualtest]
