= Park Junhyuk - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Clubhub

---

== Overview

Clubhub is a desktop application for managing members, inventory, finances and events in a club.
The main targets for this application are student clubs and groups in University and it includes features (i.e. majors) that are more relatable to University setting.
Using Clubhub, users can create, edit and delete club information through the command-line interface (CLI). Graphical user interface (GUI) is also available to display these informations neatly and clearly.
The development of Clubhub was team-based and the task was divided among the 4 team members. Each member developed one of the components of the application individually while code integration and documentations were done together as a team.
Java programming language was used for the development. For the integrated development environment (IDE) and version control software (VCS), IntelliJ and Github were used respectively.


== Summary of contributions

* *Major enhancement*: reformatted and refactored existing `Person` code base in the AB4 as `Member` to fit the context of the Clubhub
 and added *new additional attributes* to each member object.

** The following attributes were added to Clubhub:
*** Major
*** Postal code

** What it does: It allows the user to add information about each member's major and postal code in the Clubhub.

** Justification: These additional attributes allow the user to store more information about the club member such as major and postalcode.
  Ability to store each member's major is relevant in a University club context as each club member is a student studying a particular major in the university. Furthermore,
  storing of each member's home postal code as a separate attribute from home address will allow easier mailing procedure.

** Highlights: This enhancement required modification in the add and edit function of the club member as they had to be adjusted to taken in the two new arguments.
New models also had to be created for these new member attributes.

* *Major enhancement*: created new `Find` features that allows the user to search for club members by major, phone number and postal code.

** The following commands were added to Clubhub:
*** findmajor
*** findphone
*** findpostalcode

** What it does: These additions enable the user to find the club members by their majors, phone numbers and postal codes. After filtration,
the graphical user interface will display the members that have the searched information.

** Justification: There are many situations when managing a University club whereby a quick advanced search is needed to look for member with a particular attribute.
With the help of the new find features, the user can now search the club members not only by their names but also their majors, phone numbers and postal codes.

** Highlights: This enhancement required creation of `MajorContainsKeywordsPredicate`, `PhoneContainsKeywordsPredicate` and `PostalcodeContainsKeywordsPredicate` models together with the
 corresponding sets of parsers and commands.

* *Minor enhancement*: changed the duplicate check feature to fit the University context of the Clubhub better.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
