= Lee Ming Liang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ProManage

ProManage is a *professional desktop application* for companies that specialises in executing projects that undergoes a
long and tedious planning phase. ProManage allow *Manager* and *Employees* of project teams to manage their team members and events easily.
ProManage is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI).


== Overview

This project portfolio documents my contributions to the development of the CS2113 project, as part of my team T16-2.

== Summary of contributions

* *Major enhancement*: Added ability to *login, logout, show user personalised event list* via the `login`, `logout` and `showmine` command
** What it does: Allow users to login according to designation
** Justification: These features allow users to use application's function according to their designation. Users who login
  with their personal email are able to list event they are listed as an attendee, therefore remove the need to go through
  the list of events to find the events they are associated with.
** Highlights: Users who are at lower privilege level are not allow to use certain commands like add event, edit event, etc.
The app will give invalid privilege error message when users attempts to use inappropriate function that does not match their privilege level.
This is useful in helping users to differentiate between incorrect input commands and insufficient privilege commands.

* *Minor enhancement*:
** Created `sort` command which allows user to sort the event list according to the parameters they entered.
This create convenient for users to find event in the event list. For example, they are able to sort events according
to their date and find events that are occurring at earlier dates.
** Created the storage components for events so that the event created could be save as XML format.
** Created the event class and it relevant components to transform the addressbook app to an event planner app.
** Updated the mainapp to load eventlist xml or a sample of events when the app launches.
** Implemented ProManageParser which parser all commands

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=IcedCoffeeBoy[Functional code]]

* *Other contributions*:

** Project management:
*** Helped to Managed releases on GitHub
*** Managed the issue tracker on GitHub by creating new issues and closed existing issues that already resolved.
*** Wrote test cases to increase coverage
   [https://github.com/CS2113-AY1819S1-T16-2/main/pull/36[PR1]]
   [https://github.com/CS2113-AY1819S1-T16-2/main/pull/56[PR2]]
   [https://github.com/CS2113-AY1819S1-T16-2/main/pull/116[PR3]]
   [https://github.com/CS2113-AY1819S1-T16-2/main/pull/144[PR4]]
   [https://github.com/CS2113-AY1819S1-T16-2/main/pull/138[PR5]]

** Documentation:
*** Updated the User Guide for Practical Exam 1
*** Updated the Developer Guide to include `sort` command, user stories for sort, login and use case for showmine,
class diagram for parser.
*** Include new test case for `login` and `sort` command for Appendix F under developer guide.


** Community:
*** PRs reviewed and merged
*** Helped other teammates to debug their code

** Tools:
*** Setting up of reponsense



== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=login]

include::../UserGuide.adoc[tag=logout]

include::../UserGuide.adoc[tag=sort]

include::../UserGuide.adoc[tag=showmine]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=Parser]

include::../DeveloperGuide.adoc[tag=Sort]






