= Ang Jie Liang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ProManage
---
== Overview

ProManage is a *professional desktop application* for companies that specialises in handling and executing projects.
ProManage allow *Manager* and *Employees* of project teams to manage their team members and events easily.
ProManage is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI).

This project portfolio documents my contributions to the development of the CS2113 project, as part of my team T16-2.

== Summary of contributions

* *Major enhancement*: added *the ability to manage and view employees' events* via the `invite`, `remove` and `select` commands
** What it does: allows the user to invite employees to events, remove employees from events, and select and view an employee's event schedule on the indicated date, month or year which is displayed on the *event list panel*.
** Justification: This feature facilitates managing and scheduling of events among teams of employees who have different work schedules, and allow managers and employees to monitor and handle their event schedules easily. Schedule conflicts can be avoided and resolved easily with this enhancement.
** Highlights: This feature considers whether the event an employee is invited to *clashes* with the particular employee's work schedule, and *guarantees* that schedule conflict will not occur. The underlying `Event` model structure implemented for this enhancement is carefully designed and allows extension commands `viewmine` and `selectEvent` to be easily implemented.


* *Minor enhancement*:
** set up the event list panel to display the events for the UI
** added the `addEvent` command, which also warns the user when the planned event clashes or coincides with other existing events at the same location and time
** improved the `editEvent` command, which warns the user when the changed time or date of the edited event leads to schedule conflicts with any of the event's attendees

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=jieliangang[Functional and Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (6 releases) on GitHub
*** Managed the issue tracker and project dashboard on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme https://github.com/CS2113-AY1819S1-T16-2/main/pull/134[#134]
*** Updated the `add` and `edit` command to distinguish employees by their unique email address
*** Updated the `find` command to also search for employees via their email address
*** Wrote additional tests for existing features to increase coverage from 82% to 87% https://github.com/CS2113-AY1819S1-T16-2/main/pull/128[#128] https://github.com/CS2113-AY1819S1-T16-2/main/pull/130[#130] https://github.com/CS2113-AY1819S1-T16-2/main/pull/131[#131]
** Documentation:
*** Updated the User Guide to include `addEvent`, `editEvent`, `invite`, `remove` and `select` command
*** Updated the Developer Guide to include implementation details, use case, user stories and instructions for manual testing for `invite` and `select` command.
*** Updated the `Model`, `UI` and `Logic` class diagram in Developer Guide
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2113-AY1819S1-T16-2/main/pull/77[#77] https://github.com/CS2113-AY1819S1-T16-2/main/pull/114[#114] https://github.com/CS2113-AY1819S1-T16-2/main/pull/122[#122]
*** Reported feature bugs discovered during system testing (Issue: https://github.com/CS2113-AY1819S1-T16-2/main/issues/75[#75] https://github.com/CS2113-AY1819S1-T16-2/main/issues/125[#125] https://github.com/CS2113-AY1819S1-T16-2/main/issues/126[#126])
*** Prepare sample data for final demo https://github.com/CS2113-AY1819S1-T16-2/main/pull/149[#149]
** Tools:
*** Integrated GitHub Plugins (Coveralls, Travis CI, AppVeyor)
*** Automated team documentation build on GitHub pages


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=invite]

include::../UserGuide.adoc[tag=remove]

include::../UserGuide.adoc[tag=select]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=Storage]

include::../DeveloperGuide.adoc[tag=Model]

include::../DeveloperGuide.adoc[tag=Invite]



