= Kelvin Tan - Project Portfolio
:site-section: AboutUs
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]

:repoURL: https://github.com/CS2113-AY1819S1-T12-3/main/tree/master


Project: Jalil Enterprises Stock List

== Overview

=== Project Overview

This project was a part of the CS2113T (Software Engineering & Object-Oriented Programming) module, and our team was tasked to enhance the existing AddressBook application for a specific target audience group of our choice.

=== Product Overview

Morphed from AddressBook – Level 4 [link to AB4], Jalil Enterprises is a desktop inventory list application used for recording stocks in NUS Computer Engineering laboratories. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java and has ~10 kLoC.

Some key features of the Jalil Enterprises application are storing quantities and statuses of stocks, creating loan lists for loaning of equipment, and saving and viewing archives of the inventory on command.

== Summary of contributions
For the project, I was responsible for the storage component of the application as well as the implementation of “saving and viewing a version of the stock list” feature.

* *Major enhancement*: : Implemented a series of commands which allow the user to *save and view past versions of the inventory*.
** What it does: allows the user to save the current inventory as a .xml file and open it anytime in a table format.
** Justification: This feature improves the product significantly because a lab technician would need to save and review past inventory statuses monthly.
** Highlights: This enhancement affects both storage and events management. It required an in-depth analysis of storage designs and XML transformations with XSLT. The implementation too was challenging as it required the creation of new commands.

* *Other contributions*:

** Project management:
*** Managed project releases `V1.0` – `V1.3` on GitHub
*** Responsible for milestone completion on GitHub
** Enhancements to existing features:
*** Enhanced FindCommand to search for items with a partial keyword

    Example: find “ardui” -> returns Arduino item

*** Wrote tests for SaveCommand to increase coverage (Pull requests https://github.com/CS2113-AY1819S1-T12-3/main/pull/112[#112])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=savecommand]

include::../UserGuide.adoc[tag=opencommand]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=saveopen]


