= Kenneth Chua Song Jye - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

== PROJECT: Book Inventory

---

== Overview

_BookInventory_ is a *multi-platform* desktop application catered *primarily* for store owners to manage their book supplies. It includes many features such as adding, deleting and requesting of books in the inventory. Users interact with _BookInventory_ using *Command Line Interface (CLI)*, and has a *Graphic User Interface (GUI)* created with JavaFX.

_BookInventory_ was developed by a team of four students over a period of one semester. The original source code was adapted from the Address Book (Level 4) project by SE-EDU. It started as a project for the following modules offered by the School of Computing, National University of Singapore:

* *CS2101* - Effective Communication for Computing Professionals

* *CS2113* - Software Engineering & Object-Oriented Programming

This Project Portfolio documents my contributions and demonstrates my ability to write documentation for both User Guide and Developer Guide for _BookInventory_.

== Summary of contributions

* *Major enhancement*: added *the ability to conveniently stock, sell and delete books* from the inventory
** What it does: users can execute `stock`/`sell`/`delete` commands by selecting the book either from a list or with their unique ISBN. To facilitate the typing of ISBN, users can cycle through existing ISBNs in the inventory by pressing kbd:[Tab].
** Justification: These features improve the product significantly as books are bought and sold *daily* which make them the core functions of _BookInventory_. As such, there should be a more convenient way to execute them.
** Highlights: This enhancement affects existing commands and commands to be added in future. The implementation was challenging as it required changes to existing commands.

* *Minor enhancement*: added *the ability to display a list of books less than or equal to a given quantity* using the `check` command.

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=kennethcsj[Functional/Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (5 releases) on GitHub.
** Additional enhancement to existing features:
*** Added a new cost field to the `add` command.
*** Enhanced `delete` command to allow delete by Isbn.
*** Enhanced `edit` command to prevent direct edits to quantity.
*** Enhanced `find` command to allow substrings as an input to find for books.
** Documentation:
*** Updated the initial User Guide to be a representation of _BookInventory_.
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2113-AY1819S1-T12-3/main/issues/174[1], https://github.com/CS2113-AY1819S1-T12-3/main/issues/176[2], https://github.com/CS2113-AY1819S1-T12-3/main/issues/182[3], https://github.com/CS2113-AY1819S1-T12-3/main/issues/196[4])
*** Some parts of the kbd:[Tab] feature I added was adopted by several other classmates

== Contributions to the User Guide

_This part shows the sections that I contributed to the User Guide. My ability to write documentation targeting end-users are showcased here._

include::../UserGuide.adoc[tag=check]

include::../UserGuide.adoc[tag=sell]

include::../UserGuide.adoc[tag=tabfeature]

== Contributions to the Developer Guide

_This part shows the sections that I contributed to the Developer Guide. My ability to write technical documentation and the technical depth of my contributions are showcased here._

include::../DeveloperGuide.adoc[tag=checkcommand]

include::../DeveloperGuide.adoc[tag=sellcommand]

include::../DeveloperGuide.adoc[tag=tabfeature]
