= Kenneth Chua Song Jye - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

== PROJECT: Book Inventory

---

== Overview

This Project Portfolio summarises my overall contributions to _BookInventory_. _BookInventory_ is a *multi-platform* desktop application catered *primarily* for store owners to manage their book supplies - adding, deleting, requesting of books, etc.. Users interact with _BookInventory_ using *Command Line Interface (CLI)*, and has a *Graphic User Interface (GUI)* created with JavaFX. This application was developed by a *team of four* students over a semester with the original source code adapted from the Address Book (Level 4) project by SE-EDU.

== Summary of contributions

This section records my contributions for _BookInventory_.

* *Major enhancement*: added *the ability to conveniently stock, sell and delete books* from the inventory
** What it does: users can execute `stock`/`sell`/`delete` commands by selecting books' unique ISBN. To facilitate typing, users can also cycle through existing ISBNs by pressing kbd:[Tab].
** Justification: As books are bought and sold on a *daily* basis, there should be a faster and more convenient way executing them in _BookInventory_.
** Highlights: This enhancement affects existing commands and commands to be added in future. The implementation was challenging as it required changes to existing commands.

* *Minor enhancement*: added *the ability to display a list of books less than or equal to a given quantity* using the `check` command.

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=kennethcsj[Functional/Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (5 releases) on GitHub.
** Additional enhancement to existing features:
*** Added a new cost field to the `add` command.
*** Enhanced `delete` command to allow delete by Isbn.
** Documentation:
*** Updated the initial User Guide to be a representation of _BookInventory_.
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2113-AY1819S1-T12-3/main/issues/174[1], https://github.com/CS2113-AY1819S1-T12-3/main/issues/176[2], https://github.com/CS2113-AY1819S1-T12-3/main/issues/182[3], https://github.com/CS2113-AY1819S1-T12-3/main/issues/196[4])
*** Some parts of the kbd:[Tab] feature I added was adopted by several other classmates

== Contributions to the User Guide

_This part shows the sections that I contributed to the User Guide. My ability to write documentation targeting end-users are showcased here._

include::../UserGuide.adoc[tag=check]

include::../UserGuide.adoc[tag=sell]

include::../UserGuide.adoc[tag=tabfeature]

== Contributions to the Developer Guide

_This part shows the sections that I contributed to the Developer Guide. My ability to write technical documentation and the technical depth of my contributions are showcased here._

include::../DeveloperGuide.adoc[tag=checkcommand]

include::../DeveloperGuide.adoc[tag=sellcommand]

include::../DeveloperGuide.adoc[tag=tabfeature]
