= Mohamad Aslam Bin Mohamed Johan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Trajectory

---

== Overview

Trajectory is a lightweight learning management system for those who need a
no-frills solution for managing students, modules, grades, classes and notes.
It is built for users who prefer typing (CLI) over GUI interaction and has a GUI created with JavaFX.

== Summary of contributions

* *Major enhancement*: implemented Student and Course Management
** What it does: allows a faculty member to manage students, and courses within an institution.
** Justification: Unlike AB4 which has a generalized target audience, the feature I implemented are written for the context of an LMS.
Built specifically for the needs of teachers, and by extension -- the needs of an educational institution.
** Highlights: Cohesiveness with other features as they make use of the student/course APIs for their own use.

* *Minor enhancement*: added the ability for the user to lock/unlock the system to prevent unauthorized use.
* *Minor enhancement*: wrote a custom implementation of the storage-level layer for the team to use.
* *Minor enhancement*: built an utility class for the rendering of data into HTML (Bootstrap).

* *Code contributed*: https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=m-aslam-mj2[Project Code Dashboard]

* *Other contributions*:

** Project management:
*** Initial setup of continuous integration platforms (Travis, AppVeyor), coverage platform (Coveralls) and code quality platform (Codacy).
*** Initial setup of GitHub issue tracker.
*** Setup of somewhat-strict code review system, which requires sign-off by Travis, AppVeyor and Codacy and additionally requires another team member to personally perform peer review before code may be merged into the organization repository.
*** Managed milestones for the project, and ensured that required deliverables are ready.
*** Managed releases `v1.2` - `v1.3.2` (5 releases) on GitHub
** Enhancements to existing features:
*** revamped existing AB4's commands to fit the theme of the product (e.g. add to student add)
** Documentation:
*** Updated project-wide sections for both the UG and the DG.
** Community:
*** PRs reviewed and approved.

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=studandcoursemanagement]

include::../UserGuide.adoc[tag=studandcoursemanagementsummary]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=umsimplementation]

include::../DeveloperGuide.adoc[tag=studcourseusecases]

