= Melvin Tan Jit Chong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NUSSU-Connect

---

== Overview

The purpose of this portfolio is to document a summary of my contributions to the project. This project is a software
engineering project that aims to solve some of the common issues that NUSSU is facing.
NUSSU-Connect is an application for executive committee (exco) members of the NUS Student Union (NUSSU) to help them perform their daily tasks including managing recruitment, contacts, budgets and projects efficiently.
Other team members working on this project are Jonathan Ng Hian Leong, Sanjukta, and Soh Boon Jun.

=== List of Features

[width="59%",cols="22%,<23%,<25%,<30%",options="header",]
|=======================================================================
|Feature |Feature description |Format | Example
|Logging into system |Logs into application using relevant credentials |`login USERID PASSWORD ROLE` |`login X1234567X zaq1xsw2cde3 member`

|Creating a new user account |Creates a new user account in the address book |`createaccount USERID PASSWORD ROLE` |`createaccount X1234567X aq1xsw2cde3 member`

|Search Pruning |Trim the list of contacts with every successive find command without the hassle of typing a long single line command |`find \tag ROLE` |`find \tag President`

|Undoing Search Commands |Restores the displayed list to the state before you perform your most recent find command |`undosearch` |

|Submitting data for budget allocation |Submits the data about number of events, expected turnout etc |`budget c/CLUB NAME t/TURNOUT e/NUMBER OF EVENTS` |`budget c/Computing Club t/200 e/5`

|Calculating the budgets |Calculates the budgets for all the clubs in the address book using the total available budget |`calculatebudget b/TOTAL AVAILABLE BUDGET IN SGD` |`calculatebudget b/50000`

|Viewing the allocated budget |Shows all the allocated budgets to the user |`viewbudget` |

|Submitting grant request |Submits data about amount of grant needed, the reason and tags the importance level |`request m/AMOUNT r/REASON t/IMPORTANCE LEVEL` |`request m/1000 r/for booking auditorium t/medium`

|Viewing grant request |Shows a list of all the grant request sorted by order of importance, and if there is a tie, by descending order of amount requested |`viewrequest` |

|Accepting grant request |Approves a specific grant request from the list of grants |`accept [-a all] [INDEX]` |`viewrequest` + `accept 2`

|Adding person's skill |Edits a person's skill in the address book |`asl INDEX s/SKILL l/SKILL_LEVEL` |`asl 2 s/Photography l/30

|Locating persons |Finds persons in the displayed list whose names/tags contain any of the given keywords |`find [\tag] [\exclude] KEYWORD [MORE_KEYWORDS]` |`find \tag President`

|=======================================================================


== Summary of contributions

== Preface
This section shows the various contributions made to the project, covering aspects such as enhancement features, codes contributed and other forms of contributions.

* *Major enhancement*: added *the ability to securely log into the application with the relevant login credentials with a specific level of access to the application features associated with the login credentials*
** What it does: allows you to login into the application with a specific role so you are only able to access role-specific features within the application.
** Justification: This feature improves the product in terms of security significantly because it prevents any random user who does not possess the correct login credentials to be able to access the application.
Due to the fact that you can only log into the application with your relevant role, it prevents any unauthorized access to other features that are only accessible for other roles.
** Highlights: This enhancement is first designed, taking into consideration the security and practicality aspects that are highly specific to NUSSU committee members, which is our target user group.
There were a few challenges, namely the addition of new commands within the enhancement itself such as deletion of accounts and changing of account passwords, and
the way account credentials are encrypted. Owing to the project time constraints, a simpler encryption algorithm, compared to traditional encryption algorithms which are stronger, is used.
The current choice of the encryption methodology of login credentials ensures the security enhancement is still feasibly robust, yet does not demand an excess of time spent working on it.
** Credits:

* *Minor enhancement*: added a create account command within the application.
** What it does: allows you to create a new account with your desired login credentials so that you can log into the application securely.
** Justification: This feature allows you to be able to create their own accounts so that you do not need to rely on the accounts of other users in order
to log into the application.
** Highlights: Similar to the major enhancement, this minor enhancement is designed in light of practical considerations of the committee members of NUSSU.
It is impractical for NUSSU, which consists of a numerous number of members, to all use the same account to log into the application. Without the account creation
enhancement, the multi-user access level feature within the login system would not be utilized at all. There should be multiple accounts with different roles that fit
different committee members with varying levels of authority within NUSSU, so that a member can create an account with an application access level relevant to his role
in NUSSU only.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
*** Set up issue tracker for the team repository
*** Set up organization directory and team repository on GitHub
*** Set up continuous integration (CI) tools (Travis) and (Appveyor) on the team repository
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the login's multi-user access level feature I added was adopted by several project group mates (https://github.com[1], https://github.com[2])
*** Renamed the product to "NUSSU-Connect"
*** Gave suggestions to reduce the time needed to create UML diagrams (ObjectAidUM as an Eclipse framework)
** Tools:

== Contributions to the User Guide

== Preface
This section will touch on two commands that you can use, namely the `login` and `createaccount` command. The `login` command allows you to log into the application securely
using your own login credentials. The `createaccount` command allows you to create a new account with your own desired login credentials.

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=logincreateaccount]

include::../UserGuide.adoc[tag=login]

== Contributions to the Developer Guide

== Preface
This section will touch on two commands that you can use, namely the `login` and `createaccount` command. The `login` command allow you to log into the application securely
using your own login credentials. The `createaccount` command allows you to create a new account with your own desired login credentials.

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=login]
