= Ming Xun Seah - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: RecruitBook

---

== Overview
This project portfolio page serves to document my contributions to the project "RecruitBook". The project was created for the "CS2113T: Software Engineering & Object-Oriented Programming" module that I took during my second year of study in the National University Of Singapore(NUS).
RecruitBook is referenced from AddressBook 4 created by the SE-EDU team from NUS and it is then further developed by my team.

My team consists of 5 members who majored in the field of Computing and we each handled different aspects of RecruitBook ranging from its Graphical User Interface(GUI) to its core functionalities.
My role as a developer in this project was to manage the modifying and handling of data. I had to ensure that different components are properly integrated in such a way that any data modifications would be propagated throughout RecruitBook. This ensures that the data present in RecruitBook is always consistent.

RecruitBook is a desktop application created for job agents. It serves as a management tool to better manage both a list of job applicants and job offers. The user interacts with it using a Command Line Interface, and it has a GUI created with JavaFX. It is written in Java, and has about 10k lines of code.

Currently, these are the features available in RecruitBook:

* Adding and deleting of data, modifying of data, fetching of data, shortlisting, emailing and blacklisting

== Summary of contributions

* *Major enhancement*: added *the ability to edit entries*
** What it does: +
It allows the user to edit details of candidates, companies and job offers
** Justification: +
This feature gives users the freedom to update the saved data in RecruitBook, making it easier to manage the different lists as over time, entries might require changes. Any unwanted typing mistakes or misinformation can be easily rectified as well.

** Credits: https://github.com/nusCS2113-AY1819S1/addressbook-level4[AB4]

* *Major enhancement*: added *the ability to sort entries*
** What it does: +
It allows users to sort the various lists (candidate, company or job offers) by different attributes such as their names.
** Justification: +
This feature enables users to control how they want their lists listed. It makes it easier to determine how different entries compare to one another by sorting them based on selected attributes.
** Highlights: +
Apart from the attributes, users can also do a reverse sort to list out the current list in reverse order (both increasing and decreasing order).

* *Minor enhancement*: +
** Added a *Blacklist Command* that blacklists undesired candidates. Serves like a blocking feature that prevents users from carelessly shortlisting or editing these candidates. Blacklisted candidated are tagged with "BLACKLISTED".

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=mingxunseah[Functional code]] [https://github.com/CS2113-AY1819S1-F09-4/main/tree/master/src/test[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases (by milestones) `v1.1` - `v1.3.1` (3 releases) on GitHub
** Enhancements to existing features:
*** Added a list of enums for the education level attribute in RecruitBook. Makes sorting by education level easier.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=sort]

include::../UserGuide.adoc[tag=blacklist]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=edit]

include::../DeveloperGuide.adoc[tag=sort]

include::../DeveloperGuide.adoc[tag=blacklist]

