= Ming Xun Seah - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: RecruitBook

---

== Overview

RecruitBook is a desktop address book application created for job agents to better manage both a list of job applicants and job offers. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to edit entries*
** What it does: +
It allows the user to edit details of candidates, companies and job offers
** Justification: +
This feature gives users the freedom to update the saved data in RecruitBook, making it easier to manage the different lists as over time, entries might require changes. Any unwanted typing mistakes or misinformation can be easily rectified as well.

** Credits: https://github.com/nusCS2113-AY1819S1/addressbook-level4[AB4]

* *Major enhancement*: added *the ability to sort entries*
** What it does: +
It allows users to sort the various lists (candidate, company or job offers) by different attributes such as their names.
** Justification: +
This feature enables users to control how they want their lists listed. It makes it easier to determine how different entries compare to one another by sorting them based on selected attributes.
** Highlights: +
Apart from the attributes, users can also do a reverse sort to list out the current list in reverse order (both increasing and decreasing order).

* *Minor enhancement*: +
** Added a *Blacklist Command* that blacklists undesired candidates. Serves like a blocking feature that prevents users from carelessly shortlisting or editing these candidates. Blacklisted candidated are tagged with "BLACKLISTED".

* *Code contributed*: [https://github.com/CS2113-AY1819S1-F09-4/main/tree/master/src/main[Functional code]] [https://github.com/CS2113-AY1819S1-F09-4/main/tree/master/src/test[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases (by milestones) `v1.1` - `v1.3` (3 releases) on GitHub
** Enhancements to existing features:
*** Added a list of enums for the education level attribute in RecruitBook. Makes sorting by education level easier.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=sort]

include::../UserGuide.adoc[tag=blacklist]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=edit]

include::../DeveloperGuide.adoc[tag=sort]

include::../DeveloperGuide.adoc[tag=blacklist]

