= Nguyen Ngoc Linh Chi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:stylesheet: gh-linhchi-pages.css


== PROJECT: SAVEE - Financial Planner

== Overview:

The NUS CS2113T - Software Engineering and Object Oriented Programming module provided a valuable hands-on experience in developing desktop applications. In groups of 4 - 5 students, guidelines were given out periodically over 10 weeks to shape a user-group-focused application. The objective of the project was to modify a pre-existing general source code https://nuscs2113-ay1819s1.github.io/addressbook-level4/[AddressBook Level 4]  into a useful program. Desktop application `Savee` aims to help its users manage their financial status with the motto *Savvy the money*. It is currently designed for *students*. The User and Developer Guides were also written to emulate some of the actual work schedules involved in the public release of an official product.

This application enables users to organize data with the command line interface (CLI). *Name*, *date*, *money flow*, and optional *tag* can be recorded. Each record must consists of *name*, *date*, *money flow*. The date component refers to the actual date when the financial activity was performed and the money flow component refers to the income or expenditure. Users will have the opportunity to consider their expenses and possibly become more aware of their financial status. Users will also be able to insert a command into the system using the text box located at the topmost of the Savee application. A Graphic User Interface (GUI), created by JavaFX, will be used to display output of the system so as to create an instinctive and engaging user experience.

When you read User guide and Developer guide, you might be confused as our application has 2 names, Financial Planner and Savee. Both names refers to the app. Savee is the official name of the app when it is marketed for the users. FinancialPlanner is the name used when referring to the app in the developer guide and code.

== Summary of contributions:

Milestones were set every fortnight. Each member was expected to contribute to the project in every milestone and work as a team. A summary of my contributions are given below.

=== Enhancement-related contributions:

*_Major enhancements_* : Morphed the AddressBook4 to Savee.

** `Reason for enhancement`: To enable Savee to keep track of the daily financial activities of the user..
** `Overview`: Significant effort was required to morph this application.
** `Highlights`: A long time was required to read through all 10 kLoc to understand and modify the code.
** `My contributions`: I re-factored functions together with variables across classes to make the components compatible and consistent for the application. I also re-structured the code.


*_Major enhancements_* : Added the feature that allows the user delete all the record whose date is same as date entered.

** `Reason for enhancement`:The application is designed for daily expense/income management. In case the user types in a wrong date at the beginning. This feature allows user to delete multiple records at the same time, compared to the original delete one record at the time.
** `Overview`: I developed this enhancement with the hope to increase the user-friendliness of the application by decreasing the time spent on delete feature.
** `Highlights`: This major enhancement was simple to code but unexpectedly difficult to debug as it requires a in-depth knowledge for the Internal List structure building up the list of records, and pointer when looping through the list and deleting records.
** `My contributions`: I wrote the code for the command, parser, and tests, and modify other classes and codes to adjust when a new command is added.

*_Major enhancements_* : Added the feature that allows the user archive the record data from Savee to the Excel file.

** `Reason for enhancement`: The feature lessens the memory burden of the computer by enabling users to store large amounts of data out of the computer. Users will also be able to share record data with their friends and family members.
** `Overview`: The feature allows users to archive the data in excel file, this Excel file can be saved in other locations (e.g., external computer drive, google drive, one drive)
** `Highlights`: This major enhancement requires significant effort and time, as initially, the library is not included in Java 10 library, I have to read the documentation as well as learn how to utilize the library in the short time. Therefore, it is reasonable to consider this feature as *advanced* feature. Effort was also spent on designing a user-friendly Excel file.
** `My contributions`: This feature can take in *6 different input modes*. This complexity also opens many different routes of errors and much time was spent on testing and debugging.
** `Credits`: Apache Poi Library and its inner class were used and modified to fit into the feature.


*_Major enhancements_* : Added the feature that allows the user import the record data from the Excel file to the Savee.

** `Reason for enhancement`: To enable users to import data back into Savee. There will be unlimited number of sheets that can be imported.
** `Overview`: The feature allows user to import the record data from the Excel file.
** `Highlights`: Similar to the archive feature, a significant effort and time was spent to read and utilize the required documentation. The existence of the directory path of the Excel file was also examined.
** `My contributions`: This feature takes in *2 different input modes*. I have set up the pre-conditions for the Excel file to be successfully imported [refer to the *User guide*].
** `Credits`: Apache Poi Library and its inner class were used and modified to fit into the feature.


*_Major enhancements_* : Added the feature that allows the user export the record data from Savee to the Excel file.

** `Reason for enhancement`: Users will also be able to share record data with their friends and family members through Excel file.
** `Overview`: This feature allows user export data into Excel file.
** `Highlights`: Similar to the archive feature, a significant effort and time was spent to read and utilize the required documentation. Effort was also spent on designing a user-friendly Excel file.
** `My contributions`: This feature takes in *6 different input modes*. This complexity also opens many different routes of errors and much time was spent on testing and debugging.
** `Credits`: Apache Poi Library and its inner class were used and modified to fit into the feature.

*_Minor enhancement_* : Added the feature that automatically draw a line chart in the Excel file.

** `Reason for enhancement`: A line chart into Excel file will be drawn next to the summary data after executing the `exportexcel` or `archive` command. This line chart will offer the user a visual display of income, outcome and net financial status based on date.
** `Overview`: This feature will draw a line chart about the summary of Income, Outcome, and Net based on Date.
** `Highlights`: : This major enhancement requires significant effort and time, as initially, the library is not included in Java 10 library, I have to read the documentation as well as learn how to utilize the library in the short time. Therefore, it is reasonable to consider this feature as *advanced* feature.
** `My contributions`: This feature does not take in any input, as it will be automatically drawn after the Excel file is created, meaning that user enter the `exportexcel` command or `archive` command.
** `Credits`: Apache Poi Library and its inner class were used and modified to fit into the feature.

*_Code contributed_* :
https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=nguyenngoclinhchi

=== Non-enhancement related contributions:

* *_Project management_* :
** Raised milestones and organized the group to complete each milestones before deadline.
** Ensured that milestone objectives were met and submitted to relevant PRs to module repo
** Managed releases for 1 milestone (`v1.3`)

* *_Enhancements to existing features_* :
** Wrote additional tests for existing or new features to increase coverage

* *_Documentation_* :
** Did cosmetic tweaks to existing contents of the User Guide and Developer Guide.
** Proof-read, organised documentation to maintain its coherence.

* *_Tools_* :
** Integrated a third party library (Apache Poi) to the project and the team repo

* *_Debugging team members code_* :
** Debugged other team member's code and offer suggestions when they are stuck
** Provided ideas for possible implementation for other team member's features

* *_Team Management_* :
** Coordinated some team meetings
** Ensured that team members meet feature deadlines set within the team

== Contributions to the User Guide:

*_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._*


include::../UserGuide.adoc[tag=deletedate]

include::../UserGuide.adoc[tag=exportexcel]

include::../UserGuide.adoc[tag=import]

include::../UserGuide.adoc[tag=archive]

include::../UserGuide.adoc[tag=draw_line_chart]

== Contributions to the Developer Guide:

*_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._*

include::../DeveloperGuide.adoc[tag=deletedate]

include::../DeveloperGuide.adoc[tag=exportexcel]

include::../DeveloperGuide.adoc[tag=import]

include::../DeveloperGuide.adoc[tag=archive]

include::../DeveloperGuide.adoc[tag=draw_line_chart]
