= Nguyen Ngoc Linh Chi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:stylesheet: gh-linhchi-pages.css


== PROJECT: FinancialPlanner

== FinancialPlanner - Overview:

In semester 1 year 2, I had a chance to learn NUS CS2113T - Software Engineering and Object Oriented Programming module. Thanks to this module, I had an hand-on experience to develop a desktop application with my teammate. Guidelines are given during 10 weeks to assist us create the application focusing on a particular group of users.

4 - 5 students from all walk of life are assigned to one group. We adjust each other working style within few weeks and support each other to develop the project. Be it minor enhancement or major enhancement, we are expected to contribute to the team.

Initially, a source code https://nuscs2113-ay1819s1.github.io/addressbook-level4/[AddressBook Level 4] is given to us at the beginning of the CS2113T module. This has about 10 kLoc. Choosing the morphing direction, we were tasked to modify the existing code into other software we opted to.

We would be evaluated based on our ability to work with existing base code and the quality of our new enhancements to
the existing code. Besides code, we were expected to write a User Guide and Developer Guide as well for the product
as though we were releasing an official product for public usage to simulate an actual work schedule.

FinancialPlanner's target is for everyone who needs help to manage their financial status, but we focus mainly on *students*. As a NUS student, I understand how great impact finance can impose on a student. With this application, I, myself and my teammate, hopes to bring positive support to users.

This application is perfectly designed for users who like typing and are proficient in organizing their data with command line interface (CLI). User can store `name`, `date`, `money flow`, and optional `tag`. With 3 compulsory components, namely, `name`, `date`, `money flow`, we create a `Record`. Typing might be time-consuming but it allows user have a glimpse back to the expense user spent or received. Hence, the user will have a chance to recall their expenses as well as be more aware about their financial status.

Locating at the topmost of the Financial Planner application is the text box, which user can use to type the command into the system. Graphic User Interface (GUI) created by JavaFX is the main component used to display output of the system to create a instinctive and engaging user experience.

== Summary of contributions

Milestone is set every fortnight. Be it minor enhancement or major enhancement, every member is expected to contribute to the project every milestone. Working as a team, I am so happy to see the development of my teammate, and also satisfied to see myself grow through the progress.

A summary of my contributions is given below.

=== Enhancements:

* *Major enhancements*: Assisted morph the AddressBook4 to FinancialPlanner
** `Reason for enhancement`: Different from the AddressBook4, which stores the contact data, our app mainly aims supporting users who prefer to keep track of their daily financial activity.
** `Overview`: Significant effort is required to morph this application. Our group did join hand to make this success.
** `My contributions`: I refactored function together with variables across classes, to make these components compatible and consistent for the application. Along the way I developed my code, I have to adjust to the new structure of the Financial Planner, as not only we did rename the variable, methods, classes, we also build up our own structure for the application.

* *Major enhancements*: Added the feature that allows the user delete all the record whose date is required.
** `Reason for enhancement`: As this application is designed for daily expense management and in case when user type in wrong date at the beginning. This feature allows user to delete multiple records at the same time, compared to the original delete one record at the time.
** `Overview`: This requires a in-depth knowledge for the Internal List structure building up the list of records, and pointer when looping through the list and deleting records.
** `My contributions`: I wrote the code for the command, parser, tests. The coverage for these class is 100%.

* *Major enhancements*:
** `Reason for enhancement`:
** `Overview`:
** `My contributions`:

* *Code contributed*:

=== *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
