= (Oscar)Zeng Hao - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets/
:stylesheet: gh-pages-oscar.css

== PROJECT: FinancialPlanner

== Financial Planner Overview

FinancialPlanner is a PC software specially designed for students who love typing.
This purpose of this product is to help users better manage their finances, including their daily spend and income.
Users are able to record their finances and modify these records, set and modify limits, summarize their financial status and export their records into excel file.
The product is based on Command Line Interface (CLI), users are able input their commands and related information at the TextBox.
Graphic User Interface is used for displaying statistic and other information, which will provide user with a clear and direct understanding about their financial status.
This product is user-friendly, the command can be automatically completed, limits will check automatically and report any exceeded limits' details.
It is also an effective and helpful product, users are able to find check their records and limits, generate summary for any period of time and export the record
to excel file to further manage these data and import excel file back.

This project is under the NUS CS2113 (Software Engineering & Object-Oriented Programming) module.
This module provides students with basic knowledge about Object-Oriented Programming and necessary software engineering training.
Students were asked to form a group with four members and develop a production with the base code https://nuscs2113-ay1819s1.github.io/addressbook-level4/[AddressBook Level 4] provided.
As a group we decided to morph the original product into FinancialPlanner.

== Summary of contributions

To better develop the product, each group member was assigned a main feature to develop. I made significant contribution to the product by constructing the limit functions.
Detailed information about my contributions is listed below.

=== `completed` *Major enhancement #1*: added the ability to set limits for multiple periods of time.

** What it does: allows the user to set multiple limits for different periods of time or a single day to better manage their spend.
All the limits will be stored and automatically checked whenever the records were updated.
The user will be reminded if any of the limits have been exceeded.
** Justification:This feature improves the product significantly because the user no longer .
This feature is challenging because it requires me to build a storage for limits to store limits' details and read from the storage.
Besides that, I also need to keep limits' information updated whenever there is a change of records and generate output if any limit has been exceeded.
** Highlights: This enhancement is the foundation of all the features below. It affects existing commands, commands to be added in future, and storage. A new xml file will be created to store all the limits. It required an in-depth analysis of design alternatives.


=== `completed` *Minor enhancement #1*: added the ability to delete limits.

** What it does: allows the user to delete existing limits. Users are able to delete certain limits by according to the
two dates.
** Justification: This feature improves the product significantly because the user need to delete the limits that will be no longer used in the future.

=== `completed` *Minor enhancement #2*: added the ability to edit limits.

** What it does: allows the user to change the limit money of existing limits. Users are able to edit certain limits by according to the two dates they.
** Justification: This feature improves the product significantly because the user may need to adjust their plan accordingly.

=== `completed` *Minor enhancement #3*: added the ability to check all limits' condition.

** What it does: allows the user to check all the existing limits' condition.
** Justification: This feature improves the product significantly because the user is able to check all the limit he/she had set.

=== `completed` *Major enhancement #2*: added the ability to set the monthly limit.

** What it does: allows the user to set the continuous monthly limit which will always check the total spending for the
current month. For example, if the limit was set to be 200 at April, the limit will check the total spend for April.
When the time comes to May, the limit will no longer check April, instead, the limit
will check the total spend of May until the last second of May.
The user will be reminded if any of the limits have been exceeded.
** Justification:This feature improves the product significantly because user will be able to make plans for their expense in advance and store all the limits.
Since user may need to set limits for multiple periods of time while it is hard to remember all the limits they have set.
This will help user better control their spend and keep their limits updated.
This feature is challenging because it requires me to build a storage for limits to store limits' details and read from the storage.
Besides that, I also need to keep limits' information updated whenever there is a change of records and generate output if any limit has been exceeded.
** Highlights: This enhancement is the foundation of all the features below. It affects existing commands, commands to be added in future, and storage. A new xml file will be created to store all the limits. It required an in-depth analysis of design alternatives.


* *Code contributed*:
Example:
https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=&sort=displayName&since=2018-09-12&until=2018-11-05&timeframe=day&reverse=false&repoSort=true[codes]

=== *Other contributions*:

** Project management:
*** Provide teammates with suggestions about their features.
*** Arrange team meetings and discussion.
** Enhancements to existing features:
*** Helped combine the storage of the FinancialPlanner.
*** Fix bugs of tests.
** Documentation:
*** Update limit related content and some other content of the User Guide and some other contents.
*** Update limit related content and of Developer Guide.

** Community:
*** PRs reviewed.
*** Contributed to forum discussions in Whatsapp group.
*** Reported bugs and suggestions for other teams in the class both in Whatsapp and Github.(examples:  https://github.com[1], https://github.com[2], https://github.com[3])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=limitfeatures]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=limitfeatures]


---

