= Sanjukta Saha - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NUSSU Connect


== Introduction

This Portfolio is a documentation of the contributions that I have made for this project, titled NUSSU Connect.

NUSSU Connect is a CLI application mainly targeted towards executive committee (exco) members of the NUS Student Union (NUSSU).
Being representatives of the NUS student body, the exco members has a part in many projects and initiatives.
This application therefore aims to help them perform some of these miscellaneous tasks that often comes from these projects much more easily.

To do so, the application comes with several features. This includes budgets/expenses management, human resource allocation and managing of important contacts.
The original source code of this project is the https://github.com/se-edu/[AddressBook-Level4] project created by SE-EDU initiative, and hence,
it also comes with some features from the AB4 project.

== Summary of contributions
My main contribution to this project is the Budgeting Feature. This intended purpose of this feature is to help the NUSSU treasurers allocate budgets fairly and equitably to all the clubs under the NUSSU based on the budget calculation data collected from the clubs.

I will further elaborate on my contributions in the following sections.

* *Major enhancement*: added *the ability for club members to submit data for budget calculation* and *calculation of the final budgets to be allocated.*

** What it does: Allows the members of clubs to submit the data - the number of events that the club is planning to hold and the expected turnout of each of these events - for the calculation of their club's budget using the `budget` command. Once data from all of the clubs has been collected NUSSU treasurers can use the `calculatebudget` command to calculate and allocate a fair and equitable budget for each of the clubs based on the total available budget.

** Justification: Managing finances is one of the most important and time consuming functions of an organization. The budgeting feature implemented in NUSSU-Connect is a simple and less tedious alternative to the present budget allocation system in place in the NUSSU. It allows

** Highlights: The `calculatebudget` command was created almost entirely from scratch. The algorithm used to equitably calculate budgets is entirely my design.

* *Minor enhancement*: added a feature that *allows club members and NUSSU treasurers to view the budget allocated to a club*.

** What it does: Using the `viewbudget` command, club members and NUSSU treasurers can enter the name of a club and view its budget.

** Justification: This command is to be used by members of clubs to view the budget allocated to their club so that they can manage their club's expenses accordingly.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Documentation:
*** Created a logo and banner for our project, NUSSU-Connect
*** Edited the AboutUs Minor, UserGuide and DeveloperGuide documents. (Pull Requests https://github.com[#12], https://github.com[#14], https://github.com[#23])

**  Others:
*** Helped teammates edit variable and constant names in order to fit the naming conventions of the Java coding standard.
*** Helped a classmate from another project group implement a way to list items according to categories.

== Contributions to the User Guide
The following sections will detail the budget allocation process while providing guidance to the users on how to use the commands that I have implemented.
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=budget]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=budget]
