= Seah Xi Qi, Nicholas - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Introduction

=== What is RecruitBook?

RecruitBook is an open-source project born out of a programming module I took in National University of Singapore.
It was created in conjunction with my teammates https://github.com/andrewome[Andrew], https://github.com/kianmengtan[Kian Meng], https://github.com/leerachel[Rachel] and https://github.com/MingXunSeah[Ming Xun].

In this project, I served the role as the team leader by steering the project direction and coordinating the implementation of features in RecruitBook.

RecruitBook is a useful Java desktop application for job agents to better organise the list of available job offers and prospective job candidates.
RecruitBook mainly uses a Command Line Interface(CLI) that allows you to interact with specific commands.
It also has a Graphical User Interface created with JavaFX and has a codebase of about 10000 lines of code.

*Link to GitHub*: [https://github.com/CS2113-AY1819S1-F09-4/main[RecruitBook]]

== Summary of contributions

* *Major enhancement #1*: added *the ability to add/delete job candidates, companies, job offers*
** What it does: +
   It allows job agents to organise information of job candidates, companies and job offers on RecruitBook.
** Justification: +
   Enables job agents to record and access required information of job candidates, job offers and companies in RecruitBook efficiently.

* *Minor enhancement #1*: +
Added a functionality that changes the logic state of LogicManager  +
* *Minor enhancement #2*: +
Added a functionality that allows user to delete multiple entries and multiple indexes +
* *Minor enhancement #3*: +
Added the ability to set a password to password protect RecruitBook +

* *Code contributed*: [https://github.com/CS2113-AY1819S1-F09-4/main/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+assignee%3Asxqnicholas96+[Pull Requests]]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=add]

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=undoredo]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=add/delete]



