= Vincent Neo Guo Zhong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:stylesheet: gh-pages-vincent.css
---

== PROJECT: Savee

== What Savee is about:

Savee is an application my team has created for the NUS module CS2113T on Software Engineering Principles and Object Oriented Programming.
Savee's main target audience are students who need help managing their finances and likes typing. In Savee,
there is a command box for inputting commands and graphic user interface(GUI)
created using JavaFX was also used to display the output of the system to create a more intuitive and engaging user experience.

== Summary of contributions
Throughout this development cycle, I have made much contributions to the team and below shows a summary of my
contributions.

=== Application Code related contributions

* *Major Enhancements*: Facilitated the morph from AddressBook Level 4 to Savee
** `Reason for the enhancement` Savee is mainly targeted at users who wants to store and keep track of their daily financial activity, which is not the same as AB4.
** `My contributions` I adapted all model and storage components. I also fixed all the tests that broke as a result of the morph.

* *Major Enhancements*: Added a feature that allows users to display a summary of their expenses and income by day, month and categories in a table
** `Reason for the enhancement` Users want to have a way to track daily or monthly financial activities without having to go through the list.
** `Brief Description` To see the summary within any date range, the user needs to enter 2 dates or 2 months and the corresponding parameters and the system would
generate a summary table.
** `My contributions` I created the framework for this feature. It covers many components comprising of parsing, data manipulation, logic and graphic user interface as output. The
report was generated on a table panel which can be switched around with other user interface panels as necessary. I created all java logic components and the Java fxml layout files.

* *Major Enhancements*: Added a feature that shows the breakdown of financial activity into categories
** `Reason for the enhancement` Savee also allows users to tag each financial activity with a tag that they can define. These tags can be used for analysing financial activity.
** `Overview` To further empower users to make informed choices, the statistics feature was designed to provide a detailed breakdown of all financial
activity within a given period.
** `My contributions` For this feature, there were 3 main parts, logic for the command, model to support statistics and the GUI. I created all the components necessary for this feature, with the most noteworthy implementation being user interface. Similar to summary,
the Ui panel in this feature can be switched out for other panels. The pie charts used were generated using JavaFX pie chart library. However, I overwrote some parts of the in to allow for greater functionality using Java's overriding feature.

* *Minor Enhancements*: Added a welcome panel that displays breakdown for current month
** `Reason for the enhancement`  Users may want to get a sense of their current financial status without having
to type a single command.
** `My contributions` I created a system to track the current date and refresh the UI panel whenever it detects changes to the underlying list.

* *Minor Enhancements*: Added an extension to list command
** `My contributions` ListCommandParser of the original implementation was tweaked slightly to allow additional functionality.

* *Code contributed* can be found here:
https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=tenvinc

=== Non-enhancement related contributions

* Project management
** Managed releases for 4 milestones(`v1.0` - `v1.3`)
** Set up a workflow where pull requests are automatically blocked unless there is one other person who approved the request

* Tools
** Set up Continuous Integration, coverage tools and github website deployment
** PRs reviewed(with non trivial comments)

* Testing
** Wrote extensive tests to increase coverage of the project

* Documentation
** Did a few cosmetic tweaks to the User Guide
** Organised and ensured that documentation is coherent

== Contributions to the User Guide
|===
|Below are some of my contributions to the User Guide. These show that I am able to write comprehensive User Guides.
|===

include::../UserGuide.adoc[tag=summary]

include::../UserGuide.adoc[tag=stats]

== Contributions to the Developer Guide
|===
|_Below are some of my contributions to the Developer Guide. These show that I am able to utilise modelling tools such as
UML diagrams, sequence diagrams, activity flow which are crucial to Software Engineering Principles to illustrate to potential
developers the architecture of my product._
|===

include::../DeveloperGuide.adoc[tag=summary]

include::../DeveloperGuide.adoc[tag=stats]

