= Vincent Neo Guo Zhong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:stylesheet: gh-pages-vincent.css
---

== PROJECT: FinancialPlanner

== What FinancialPlanner is about:

FinancialPlanner is an application my team has created for the NUS module CS2113T. In this module, we were taught basic software
engineering principles and object oriented programming. This project lasted for 10 weeks and we were tasked to develop a desktop application
for a particular group of users.

FinancialPlanner's main target audience are students who need help managing their finances.
They like typing and are often much more proficient in organising their data with command line interface (CLI). In FinancialPlanner,
there is a text box located at the topmost part of the application which users can use to type commands into the system. Graphic user interface(GUI)
created using JavaFX was also used to display the output of the system to create a more intuitive and engaging user experience.

== Summary of contributions
FinancialPlanner was adapted from https://nuscs2113-ay1819s1.github.io/addressbook-level4/[AddressBook Level 4], a sample codebase given by the module.
There were milestones to meet every fortnight and each milestone required a working product. Throughout this development cycle, I have made much contributions to the team and below shows a summary of my
contributions.

=== Application Code related contributions

* *Major Enhancements*: Facilitated the morph from AddressBook Level 4 to FinancialPlanner
** `Reason for the enhancement` FinancialPlanner is mainly targeted at users who wants to store and keep track of their daily financial activity. This is significantly
different from the original AddressBook Level 4, thus significant effort was needed to morph into FinancialPlanner.
** `My contributions` I adapted all functions that involved addition, removal and editing of the app data into functions able to process data required. I also fixed
all the tests that broke as a result of the morph.

* *Major Enhancements*: Added a feature that allows users to display a summary of their expenses and income by day, month and categories in a table
** `Reason for the enhancement` Users want to have a way to track daily or monthly financial activities without having to go through the list.
** `Brief Description` To see the summary within any date range, the user needs to enter 2 dates or 2 months and the corresponding parameters and the system would
generate a summary table.
** `My contributions` I created the framework for this feature. It covers many components comprising of parsing, data manipulation, logic and graphic user interface as output. The
report was generated on a table panel which can be switched around with other user interface panels as necessary. I created all java logic components and the Java fxml layout files for the
user interface to display correctly.

* *Major Enhancements*: Added a feature that shows the breakdown of financial activity into categories
** `Reason for the enhancement` FinancialPlanner also allows users to tag each financial activity with a category that they can define. Sometimes, users
would like to know where they are spending their money on in order to make informed decisions on their future finance activities. Since each record is tagged with
an optional set of tags, these tags can be used as categories for users to classify each financial activity.
** `Overview` To further empower users to make informed choices, the statistics feature was designed to provide a detailed breakdown of all financial
activity within a given period.
** `My contributions` For this feature, there were 3 main parts, the parsing and command logic, the model that supports the data manipulation and the user interface that
allows the users to view the output. I created all the components necessary for this feature, with the most noteworthy implementation being user interface. Similar to summary,
the Ui panel in this feature can be switched out for other panels. Furthermore, I created tabs to allow users to switch between expense and income for greater usability. The pie charts used
were generated using JavaFX pie chart library. However, I overwrote some parts of the in to allow for greater functionality using Java's overriding feature.

* *Major Enhancements*: Added a feature that allows swapping of UI panels.
** `Reason for the enhancement` For increased user friendliness, FinancialPlanner supports commands which draws charts using the in built UI. This meant that sufficient space
needed to be given to these UI panels for the chart to look right and the data points to be seen clearly. Thus, the usual approach of splitting the application in the panel is not effective.
To overcome this challenge, swapping UI algorithms were designed.
** `Overview` The swapping UI algorithm manages UI panels and decides which panels will be shown while keeping the rest hidden.
** `My contributions` The main connections between UI components and the rest of FinancialPlanner is through Google's event system. I created new classes and utilised interfaces to allow for
the switching functionality in the main UI panels.

* *Major Enhancements*: Added a welcome panel that displays breakdown for current month
** `Reason for the enhancement`  Users may want to get a sense of their current financial status without having
to type a single command. By having the panel updated, users can instantly get feedback on their current financial status whenever they add a new
record to the system. This improved the user friendliness of our app significantly.
** `Overview` This feature serves as the front page of the application. It displays the category breakdown of current month and is automatically
updated whenever the data in the application is changed.
** `My contributions` Since this feature is automatic and should not require any user input, I created new methods that can track the current date and cached all records associated with
the current month in the *ModelManager* on start up. I also hooked up this cached list to main model to listen to any changes to the underlying list and update itself as necessary. Furthermore,
I created the welcome panel UI layout and logic to read from this list whenever it updates and refresh the UI panel.

* *Minor Enhancements*: Added an extension to list command
** `Reason for the enhancement` Originally, the list command would list all records in the application. This may not be very convenient when the
number of records become very large. Thus, a more specific and user friendly command is introduced.
** `Overview` This list command allows users to specify the date range and will only show records in that range.
** `My contributions` ListCommandParser of the original implementation was tweaked slightly to allow additional functionality.

* *Minor Enhancements*: Helped to make storage more modular and combined storage for fellow teammates
** `Reason for enhancement` The storage of AddressBook Level 4 was mainly targetted at storing only one thing and it was hard to extend the feature.
** `My contributions` Thus, I created new interfaces which utilises Java's generic type to allow for greater flexibility when calling the function that saves to XML.
This broke many of the tests, and to preserve the coverage at a high level of 80%, I fixed all the tests relating to storage and combined storage for limitlist and recordlist together which is
also used by other teammates.

* *Code contributed* can be found here:
https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=tenvinc

=== Non-enhancement related contributions

* Project management
** Managed releases for 4 milestones(`v1.0` - `v1.3`)
** Set up a workflow where pull requests are automatically blocked unless there is one other person who approved the request
** Ensured that milestone objectives are met and submit relevant PRs to module repo

* Tools
** Set up Continuous Integration, coverage tools and github website deployment
** PRs reviewed(with non trivial comments)

* Debugging team members code
** Helped debug other team member's code and offer suggestions when they are stuck
** Helped provide ideas for possible implementation for other team member's features

* Team Management
** Coordinated some team meetings
** Ensured that team members meet feature deadlines set within the team

* Testing
** Wrote extensive tests to increase coverage of the project
** Wrote system tests to test integration of the system

* Documentation
** Did a few cosmetic tweaks to the User Guide
** Organised and ensured that documentation is coherent

== Contributions to the User Guide
|===
|_Below are some of my contributions to the User Guide. These show that I am able to write comprehensive User Guides._
|===

include::../UserGuide.adoc[tag=list]

include::../UserGuide.adoc[tag=summary]

include::../UserGuide.adoc[tag=stats]

include::../UserGuide.adoc[tag=welcomepanel]

== Contributions to the Developer Guide
|===
|_Below are some of my contributions to the Developer Guide. These show that I am able to utilise modelling tools such as
UML diagrams, sequence diagrams, activity flow which are crucial to Software Engineering Principles to illustrate to potential
developers the architecture of my product._
|===

include::../DeveloperGuide.adoc[tag=list]

include::../DeveloperGuide.adoc[tag=summary]

include::../DeveloperGuide.adoc[tag=stats]
