= Tsu Wei Quan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Student Management System

---

== Overview

*Student Management System (SMS)* is a desktop application which uses CLI for its interactions.
SMS allows university lectures to easily organise and manage their students and classes by allowing the lectures to easily import student lists given by their department.
SMS also provides neat features such as distributing students into groups, sending emails to them and assigning test grades.
SMS makes being a university lecturer more convenient!

== Summary of contributions

* *Major enhancement*: added *the ability to distribute all students into groups*
** What it does: This feature automatically create _n_ number of groups with balanced number of students in each group from the Management System. The user is able to distribute all students into groups with balanced gender or with balanced nationality.
** Justification: This feature proves to be useful when a lecturer wish to form students into _n_ groups for any project wor. The user can also select the condition of having balanced gender in every group if he wish to do so.
This feature was inspired during the group formation in CS2113 module where the lecturer wish to have a balanced number of a gender in every group.
** Highlights:
This enhancement itself is a new command and it does not affect existing commands. It also requires the features of creating group and adding students into group to be complete. Hence this require in-depth analysis of
group command features to allow Distribute command to be completed. The implementation started off easy as I added the nationality and gender fields into the person profile. However, the most challenging part was creating the algorithm for
the distribution process. In order to make it modular and reduce duplicate code, much time was utilized in planning and designing the algorithm.

** Credits: 3rd Party libraries were not used in this implementation. However, I have inferred a snippet of code provided on Stack Overflow.
The code that was adapted from Stack Overflow was from [https://stackoverflow.com/a/22132422/3818748[Sort a Map<Key, Value> by values]]. The code was used int `DistributeUtil.java` file,
in the `numberOfDifferentNationality` method.

* *Minor enhancement*: Added the Nationality and Gender Field into Person Object, Fixed Undo/Redo feature for Distribute Command.
* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=tsuweiquan[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
