= Xiao Yunhan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Something Daily

---

== Overview

Something Daily is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: designed *the logic (commands/ parser) for To-do List*
** What it does: the most basic components of To-do List, parser will judge which "command" function to execute and "commands" will run corresponding methods in "model".
** Justification: This enhancement is the foundation of To-do List, it provides users the way to use certain features by keying in certain commands.
** Specific features: (include add/ delete/ edit) Users can add, delete and edit certain tasks in the To-do List.

* *Major enhancement*: designed *user interface for To-do List*
** What it does: display tasks recorded in To-do List
** Justification: This enhancement make it possible for user checking tasks more visually and easier.

* *Major enhancement*: designed *the ability to sort tasks in To-do List*
** What it does: Provide users a way to sort tasks in the To-do List by certain task attribution (name, module code, deadline) and users can also reverse the rank of sorting
** Justification: This enhancement make users easier to check their tasks recorded in the To-do list based on a certain standard.

* *Minor enhancement*: add "undoable_command" class related methods to fix "undo" command on both To-do List side and Expenditure Tracker side.
* *Minor enhancement*: add a few tests to increase coverage.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Documentation:
*** Add implementation of TDL_sort command in the Developer Guide and update To-do List-related logic part in both User guide and Developer guide.
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#20], https://github.com[#24], https://github.com[#47], https://github.com[#48], https://github.com[#74], https://github.com[#78], https://github.com[#82]



== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=TDLsort]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=sorttask]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
