= (Oscar)Zeng Hao - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FinancialPlanner

== Financial Planner Overview

FinancialPlanner is a PC software specially designed for students who love typing. This product helps users better manage their finances.
Users are able to record their finances and modify these records, set and modify limits, summarize their financial status and export their records into excel file.
The product is based on Command Line Interface (CLI), users are able input their commands and related information at the TextBox.
Graphic User Interface is used for displaying statistic and other information, which will provide user with a clear and direct understanding about their financial status.

This project is under the NUS CS2113 module. This module provides students with basic software engineering training.
A group of four members was formed to develop a production with the base code https://nuscs2113-ay1819s1.github.io/addressbook-level4/[AddressBook Level 4].
As a group we morph the original product into FinancialPlanner.

== Summary of contributions

To better develop the product, each group member was assigned a main feature to develop. I made significant contribution to the product.
Detailed information about my contributions is listed below.

=== `completed` *Major enhancement #1*: added the ability to set limits for multiple period of time.

** What it does: allows the user to set multiple limits for different periods of time to better manage their spend. All the limits will be stored and automaticalky check whether the limit has been exceeded. The user will be reminded if limits have been exceeded. This feature is challenging because it requires me to build a storage for limits to store limits' details and read from the storage. 
Besides that, I also need to keep limits' information updated whenever there is a change of records and generate output if any limit has been exceeded.
** Justification:This feature improves the product significantly because user will be able to make plan for their expense in advance and store all the limits. This will help user better control their spend and keep their limits updated. 
** Highlights: This enhancement is the foundation of all the features below. It affects existing commands, commands to be added in future, and storage. A new xml file will be created to store all the limits. It required an in-depth analysis of design alternatives.

=== `completed` *Minor enhancement #1*: added the ability to delete limits.

** What it does: allows the user to delete existing limits.
** Justification: This feature improves the product significantly because the user need to delete the limits that will be no longer used in the future.

=== `completed` *Minor enhancement #2*: added the ability to edit limits.

** What it does: allows the user to change the limit money of existing limits.
** Justification: This feature improves the product significantly because the user may need to adjust their plan accordingly.

=== `completed` *Minor enhancement #3*: added the ability to list all limits' condition.

** What it does: allows the user to change the limit money of existing limits.
** Justification: This feature improves the product significantly because the user is able to check all the limit he/she had set.


=== `ongoing`  *Minor enhancement #1*: added the ability to set limit for weeks and months.
===== `sub-part of Major enhancement #1`

** What it does: allows user to set a limit for weeks and months.
** Justification: The implementation may lead to a big modification of the limit command.

=== `ongoing` *Minor enhancement #2*: develop a better UI to demo the limitlist .
===== `sub-part of Minor enhancement #3`

** What it does: provides user a better display of all limits' information.
** Justification: This implementation will help the user to have a much clearer overview of their limit details.

=== `ongoing` *Minor enhancement #3*: added the ability to change the color of the output when the limit has been exceeded..
===== `sub-part of Major enhancement #1`
** What it does: allows user to choose the color they want to color for the cells which exceed limit.
** Justification: This enhancement make some modification about the UI part.


* *Code contributed*:

=== *Other contributions*:

** Project management:
** Enhancements to existing features:
*** Helped combine the storage of the FinancialPlanner.
*** Fix some of the bugs of tests.
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed : https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=limit]

include::../UserGuide.adoc[tag=]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---


