= NUSSU Connect - Developer Guide
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/CS2113-AY1819S1-F09-1/main/

By: `Team F09-1`      Since: `Sep 2018`      Licence: `MIT`

== UML Diagrams


_{More to be added}_

== User Stories
**Must haves**

As an executive officer of NUSSU, I would like to view which other committees my applicant has applied for so that I deconflict with the other members of the Executive Committee.

As an executive officer of NUSSU, I can log into the app with the required credentials, so that I can access certain functionalities of the app exclusive to my credentials only.

As an executive member of NUSSU, I can create a new account for myself to log into the app, so that I can access the functionalities of the app.

As an executive member of NUSSU, I can delete an existing account, so that the account that is redundant will be removed from the database.

As an executive member of NUSSU, I can change the password of an existing account, so that I can make my account more secure.

As a member of NUSSU, I would like to find out how to contact another member within NUSSU so that I can work more efficiently with them.

As someone that is looking for the contact information of someone in else in a committee, I would like to filter my search such that I would only be looking through the lists of that specific committee so that I will not need to look through the whole list of NUSSU members.

As someone that takes charge of sponsors for events hosted by NUSSU, I would like to filter my search such that I would be only looking at the list of sponsors so that I will not need to look through the whole list of addressbook.

As the organizer of events, I would like to keep track of the contact information for all the helpers for that event so that I can keep them updated on the progress of the events.

As an organizer of an event, I would like to remove all users that helped with the event from my contact list so that the address book will be less cluttered.

As a member of the NUSSU treasury I would like to have a budgeting function so that I can fairly allocate budgets to the different clubs/projects

As the treasurer of a club I would like to view the budget allocated to our club so I can discuss with my teammates and seek more funds if necessary.

As the treasurer of a club I would like to be able to store the data about how many members there are in my club, how many events we are planning to hold, and the expected turn out so that we can be allocated a fair budget by the NUSSU treasury.

As the treasurer of a club I would like to use a budgeting function so that I can plan the internal events of my club efficiently.

As a member of the NUSSU treasury I would like to view requests for grants from the clubs so that I can allocate them the grant if the request is accepted by the NUSSU.

As an event organizer that is trying to find the contact details of some very specific group of people, I would like to have a search and filter function that is flexible enough so that all the search requirements can be done on the application without needing me to look through the whole list.

**Nice to have**

As the general secretary of NUSSU, I would like to have the option to backup all, or even specific segments of application data into a data file, so that in the event where accidental deletion or corruption of data occurs, I can recover the required segments of data.

As the general secretary of NUSSU, I would like to view a list of dates reserved for committee meetings planned beforehand, so that i can prepare for the meetings adequately.

As an executive member of NUSSU, I can pitch in proposal ideas into the proposal suggestions section through the community proposal voting system, so that I can find out just how popular my proposals are through the number of upvotes it receives.

As an executive member of NUSSU, I can edit current proposal ideas in the proposals section, so that i can have the option to refine current proposals.

As an executive member of NUSSU, I can delete selected proposal ideas in the proposals section, so that i can have the option to remove irrelevant proposals.

As a student in the student union of NUSSU, I want to view the list of proposals currently suggested in the proposals section and upvote those that I like, so that I can find out more about the current proposals in place and express my favor in a particular proposal.

As a student in the student union of NUSSU, I would like to be able to filter and search for proposal ideas based on keywords, so that I do not have to waste time searching through all the proposals just to find the one I want.

As the student welfare secretary of NUSSU, I would like to view statistics showing the number of students who signed up for student welfare packs, so that logistically wise, I can plan student welfare goodie events better.

As the general secretary of NUSSU, I would like to keep track of a register containing details of all members serving in the union.

As the student life secretary of NUSSU, I would like to keep track of updated statistics showing the number of students in each faculty, so that i can plan and balance the events geared towards a specific faculty, logistically and relevancy wise.

As someone that keeps track of the finances for hosting events, I would like an application that helps me simplify the process(Excel) so that I can do my work efficiently.

As someone that records what was discussed in a meeting, I would like to be able to keep a record of what everyone said, so that we can use it as a future reference for further discussion.

As someone that constantly sends email to other members of NUSSU/ Sponsors/ Public, I would like to have an access to multiple different templates of emails so that I can focus more on writing the content of the email instead of spending too much time on crafting the overall structure.

As someone that takes care of finances, I would like to have an alert system when we are running out of $$$ so that I know when I need to seek for more $$$.

As the treasurer of a club I would like to have a function that calculates the expected turnout for an event based on turnout data for similar events that we have held in the past so that I can help the NUSSU to allocate budget to my club more efficiently.

As a member of NUSSU treasury I would like to get and store the expenditure reports and bills from the sun organizations so that I can present it to auditors if need be.

As the treasurer of my club I would like to be able to view whether my request for a grant has been approved so that I can use those funds effectively.


== Use Cases

(For all use cases below, the *System* is the `AddressBook` and the *Actor* is the `user`, unless specified otherwise)

[discrete]
=== Use case: Delete person

*MSS*

1.  User requests to list persons
2.  AddressBook shows a list of persons
3.  User requests to delete a specific person in the list
4.  AddressBook deletes the person
+
Use case ends.

*Extensions*

[none]
* 2a. The list is empty.
+
Use case ends.

* 3a. The given index is invalid.
+
[none]
** 3a1. AddressBook shows an error message.
+
Use case resumes at step 2.

=== Use case: Log into system

*MSS*

1.  Address book asks user for user ID and password
2.  User types in user ID and password
3.  Address book queries and authorize user full access to address book
+
Use case ends.

*Extensions*

[none]
* 2a. User types in wrong password
+
[none]
** 2a1. Address book displays error message and exits application
+
Use case ends.

* 2b. User types in user ID for a non-existent user account
+
[none]
** 2b1. Address book displays error message and exits application
+
Use case ends

=== Use case: Create new user accounts

*MSS*

1.  User types a command to indicate intention of creating a new account
2.  Address book asks user to type in master password for enabling option to create new accounts
3.  User types in master password
4.  Address book authorizes the master password input as correct and shows successful message
5.  User types in command to create a new account with relevant user ID and password
+
Use case ends.

*Extensions*

[none]
* 2a. User decides not to create a new account and types command to indicate so
+
[none]
** 2a1. Address book cancels process of new account creation
+
Use case ends.
+
* 2b. User types in the wrong master password
+
[none]
** 2b1. Address book shows error message to user and cancels process of new account creation
+
Use case ends.
+
* 2c. User creates a new account with a user ID which already exists
+
[none]
** 2c1. Address book shows error message to user and cancels process of new account creation
+
Use case ends.

=== Use case: Delete current user accounts

*MSS*

1.  User requests to delete an existing account and types in command to do so
2.  Address book asks for confirmation to delete account with associated user ID
3.  User types command to express desire to delete account
4.  Address book deletes account associated with input user ID and respective password
+
Use case ends.

*Extensions*

[none]
* 2a. User decides not to delete an account and types command to indicate so
+
[none]
** 2a1. Address book cancels process of deleting existing account
+
Use case ends.
+

* 2b. User types in the wrong current password associated with the user ID
+
[none]
** 2b1. Address book shows error message to user and cancels process of deleting existing account
+
Use case ends.

* 2c. User wants to delete a non-existent user account
+
[none]
** 2c1. Address book shows error message and cancels process of deleting account
+
Use case ends.

=== Use case: Changing password of current user accounts

*MSS*

1.  User requests to change the password of existing user account and types in command to do so
2.  Address book asks for confirmation of password change
3.  User types command to express desire to change account password
4.  Address book changes password of account associated with input user ID and new password
+
Use case ends.

*Extensions*

[none]
* 2a. User decides not to change the password of the account and types command to indicate so
+
[none]
** 2a1. Address book cancels process of changing password of account
+
Use case ends.

* 2b. User types in the wrong current password associated with the user ID
+
[none]
** 2b1. Address book shows error message to user and cancels process of changing password of account
+
Use case ends.

* 2c. User wants to change the password of a non-existent user account
+
[none]
** 2c1. Address book shows error message and cancels process of changing password of account
+
Use case ends.

_{More to be added}_
[appendix]
== Non Functional Requirements

. Must be able to accommodate the contact details of everyone in NUSSU + 1000 extra contact details.
. All exco members of NUSSU should be able to create an account.
. Passwords must be salted and hashed with md5.
. All commands must be completed within 1 second.
. The single and multi-input commands phrases should be easy to remember and intuitive to understand what they mean.


_{More to be added}_


[appendix]

