= ProManage - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2113-AY1819S1-T16-2/main

By: `T16-2`      Since: `Sept 2018`      Licence: `MIT`

== Introduction

ProManage is a *professional desktop application* for companies that specialises in executing projects that undergoes a
long and tedious planning phase, prior to their event. This is particularly useful for companies that have a distinct structure
and chain of command. For each project, there is a project team, which is usually led by a *Manager*. The planning
committee consists of various branches such as *Admin, Logistics, Programmes, Finance, Publicity, Marketing and Safety*.

Our application aims to ease the mode of task, event allocation and management by providing an all-in-one platform for
the project team. It saves companies' time and money. Our customers will feel at ease communicating with one another in
their project team setting. There is no better way to work than a CLI application that facilitates workflow than ProManage!
More importantly, ProManage is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still
having the benefits of a Graphical User Interface (GUI). ProManage can help you manage project scheduling effectively.
Interested? Jump to the <<Quick Start>> to get started. Enjoy!

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  Download the latest `addressbook.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your ProManage App.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
+
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all employees and employers in our contact list
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named
 `John Doe` to the Address Book.
* **`delete`**`3` : deletes the 3rd person shown in the contact list list
* *`exit`* : exits the application

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which
  can be used as `add n/Some Meeting`.
* Items in square brackets are optional e.g `DEPT, [MORE_DEPTS,]` can be used as `Dept1, Dept2` or as `Dept1`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[MORE_DEPTS,]...` can be used as
 `{nbsp}` (i.e. 0 times), `Dept1`, `Dept1, Dept2` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME t/TIME`, `t/TIME n/NAME` is also acceptable.
====

[NOTE]
====
Three types priorities: `default`,`manager`,`employee` +
If login command is not executed, the priority will be `default`.
====


=== Viewing help : `help`

Format: `help`


=== Login the app: `login`
Priority level: `default`

Login to the app as one of the following identity: `manager` or `employee` +
Once login cannot logout till the app is closed.

Format: login `identity`

Example: +
`login manager`

=== Adding an employee : `add`
Priority level: `default`,`manager`


Adds an employee to ProManage +
Format/Prompts: +
Enter a command: `add` +
Enter employee details: `n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS dep/DEPARTMENT [t/TAG]...`

[TIP]
An employee can have any number of tags (including 0)

Example: +
`add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01 dep/ADMIN`

=== Editing an employee : `edit`
Priority level: `default`,`manager`

Edits the details of the employee: +
Format/Prompts: +
Enter a command: `edit PERSON_INDEX [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [dep/DEPARTMENT] [t/TAG]…​`

****
* Edits the employee at the specified `INDEX`. The index refers to the index number shown in the displayed event list. The
index *must be a positive integer* 1, 2, 3, ... +
* At least one of the optional fields must be provided.
* Name is not editable
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the employee will be removed i.e adding of tags is not cumulative.
* You can remove all the employee’s tags by typing t/ without specifying any tags after it.
****

=== Deleting an employee : `delete`
Priority level: `default`,`manager`

Delete an employee from ProManage: +
Format/Prompts: +
Enter a command: `delete PERSON_INDEX`

****
* Deletes the employee at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* 1, 2, 3, ...
****

=== Listing all employee of the company : `list`
Priority level: all

Shows a list of employee in the company +
Format/Prompts: +
Enter a command: `list`

=== Adding an event: `addEvent`
Priority level: `default`,`manager`

Adds an event to ProManage +
Format/Prompts: +
Enter a command: `addEvent` +
Enter event details: `n/NAME d/DESCRIPTION l/LOCATION date/DATE s/START_TIME e/END_TIME`  +

****
* DATE needs to be in YYYY-MM-DD format
* TIME needs to be in 00:00 format
****

[NOTE]
====
* Current checking of date format is loose. Certain invalid date may still be accepted, such as 2018-02-30.
====

Example: +
`addEvent` +
`n/Board Meeting d/Weekly Meeting l/Conference Room 1 date/2018-09-28 s/12:00 e/23:59 ` +
Creates an event named Board Meeting.


=== Modifying an event: `editEvent`
Priority level: `default`,`manager`

Edits the details of the events:
Format/Prompts: +
Enter a command: `editEvent EVENT_INDEX` +
Enter event details: `[n/NAME] [d/DESCRIPTION] [l/LOCATION] [date/DATE] [s/START_TIME [e/END_TIME]`  +

****
* Edits the event at the specified `EVENT_INDEX`. The index refers to the index number shown in the displayed event list. The
index *must be a positive integer* 1, 2, 3, ... +
* At least one of the optional fields must be provided.
* DATE needs to be in YYYY-MM-DD format
* TIME needs to be in 00:00 format
* Existing values will be updated to the input values.
****

Examples:
* Enter a command: `editEvent 10`  +
Enter event details: n/Weekly Meeting d/Check on progress l/Conference Room 2 date/2018-09-10 s/12:00 e/14:00`

=== Deleting an event : `deleteEvent`
Priority level: `default`,`manager`

Delete the specified event from ProManage. +
Format/Prompts: +
Enter a command: `deleteEvent EVENT_INDEX`

****
* Deletes the event at the specified `EVENT_INDEX`.
* The index refers to the index number shown in the displayed event list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `deleteEvent 2` +
Deletes the 2nd event in the address book.


=== Sorting all events: `sort`
Priority level: all

Sort the event listing based on the key words provided. +
Able to sort with event's name, event's date, event's starttime, event's endtime.  +
*Key word:* +
1) event's name: `name` +
2) event's data: `date` +
3) event's starttime: `starttime` +
4) event's endtime: `endtime`


Format: sort `key word` +
Example: sort name

=== Invite employees: `invite`
Priority level: `default`,`manager`

Invites an employee to an event if the employee was not previously invited. +
Format: `invite PERSON_INDEX to/EVENT_INDEX` +
Example: invite 1 to/2

****
* Invites the employee at the specified `PERSON_INDEX` *TO* the event at the specified `EVENT_INDEX`.
* The index refers to the index number shown in the displayed person list and event list respectively.
* The index *must be a positive integer* 1, 2, 3, ...
****

=== Remove employee: `remove`
Priority level: `default`,`manager`

Removes an employee from the an event if the employee was previously invited to the event. +
Format/Prompts: `remove PERSON_INDEX  from/EVENT_INDEX` +
Example: remove 1 from/2

****
* Remove the employee at the specified `PERSON_INDEX` *FROM* the event at the specified `EVENT_INDEX`.
* The index refers to the index number shown in the displayed person list and event list respectively.
* The index *must be a positive integer* 1, 2, 3, ...
* The employee to be remove must be previously invited to an event in order to be removed.
****

=== Selecting a person: `select`
Priority level: `default`,`manager`

Selects an employee and view the specified employee's events by date, year, month, month and year, or all his/her events. +
Format/Prompts: +
Enter a command: `select PERSON_INDEX` [date/DATE] [m/MONTH] [y/YEAR]

****
* Select the employee at the specified `PERSON_INDEX` and view all his/her events or events at certain time as indicated.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* `1, 2, 3, ...`
* DATE needs to be in YYYY-MM-DD format
* MONTH needs to be in 00 format (e.g. 01, 02, ... , 12)
* YEAR needs to be in 0000 format. (e.g. 2018)
* If DATE is indicated, MONTH and YEAR must NOT be indicated. Then, all events of the selected employee at the specific DATE will be displayed.
* MONTH and YEAR can be both used at the same time, resulting in events on the selected MONTH and YEAR to be displayed.
****

Examples:

* `select 1`
* `select 1 date/2018-10-31`
* `select 1 m/08`
* `select 1 y/2018`
* `select 1 y/2018 m/08`

=== Locating persons by name: `find`
Priority level: all

Finds employees whose names contain any of the given keywords. +
Format: `find KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Persons matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****


=== Listing entered commands : `history`
Priority level: all

Lists all the commands that you have entered in reverse chronological order. +
Format/Prompts: +
Enter a command: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

// tag::undoredo[]
=== Undoing previous command : `undo`
Priority level: all

Restores the event schedule to the state before the previous _undoable_ command was executed. +
Format/Prompts: +
Enter a command: `undo`

[NOTE]
====
Undoable commands: those commands that modify the event schedule's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `cancel 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `cancel 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`
Priority level: all

Reverses the most recent `undo` command. +
Format/Prompts: +
Enter a command: `redo`

Examples:

* `cancel 1` +
`undo` (reverses the `cancel 1` command) +
`redo` (reapplies the `cancel 1` command) +

* `cancel 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `cancel 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `cancel 1` command) +
`redo` (reapplies the `cancel 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Clearing all entries : `clear`
Priority level: all

Clears all entries from the event schedule. +
Format/Prompts: +
Enter a command: `clear`

=== Exiting the program : `exit`
Priority level: all

Exits the program. +
Format/Prompts: +
Enter a command: `exit`

=== Saving the data

ProManage data saves data in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add*: `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS dep/DEPARTMENT [t/TAG]...`

* *Edit* : `edit PERSON_INDEX [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [dep/DEPARTMENT] [t/TAG]…​`

* *Delete* : `delete PERSON_INDEX`

* *List* : `list`

* *addEvent* : `addEvent n/NAME d/DESCRIPTION l/LOCATION date/DATE s/START_TIME e/END_TIME`

* *editEvent* : `editEvent `[n/NAME] [d/DESCRIPTION] [l/LOCATION] [date/DATE] [s/START_TIME [e/END_TIME]`

* *deleteEvent* : `deleteEvent SCHEDULE_INDEX`

* *Invite* : `invite PERSON_INDEX to/EVENT_INDEX`

* *Remove* : `remove PERSON_INDEX  from/EVENT_INDEX`

* *Select* : `select SCHEDULE_INDEX`

* *Find* : `find KEYWORD [MORE_KEYWORDS]`

* *History* : `history`

* *Undo* : `undo`

* *Redo* : `redo`

* *Clear* : `clear`

* *Exit* : `exit`

