= ProManage - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2113-AY1819S1-T16-2/main

By: `Team 16-2`      Since: `Sept 2018`      Licence: `MIT`

== Introduction

ProManage is a *professional desktop application* for companies that specialises in executing projects that undergoes a
long and tedious planning phase, prior to their event. This is particularly useful for companies that have a distinct structure
and chain of command. For each project, there is a project team, which is usually led by a *Manager*. The planning
committee consists of various branches: *Admin, Logistics, Programmes, Finance, Publicity, Marketing and Safety*.

Our application aims to ease the mode of task, event allocation and management by providing an all-in-one platform for
the project team. It saves companies' time and money. Our customers will feel at ease communicating with one another in
their project team setting. There is no better way to work than a CLI application that facilitates workflow than ProManage!
More importantly, ProManage is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still
having the benefits of a Graphical User Interface (GUI). ProManage can help you manage project scheduling effectively.
Interested? Jump to the <<Quick Start>> to get started. Enjoy!

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  Download the latest `addressbook.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your ProManage App.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
+
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all employees and employers in our contact list
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named
 `John Doe` to the Address Book.
* **`delete`**`3` : deletes the 3rd person shown in the contact list list
* *`exit`* : exits the application

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which
  can be used as `add n/Some Meeting`.
* Items in square brackets are optional e.g `DEPT, [MORE_DEPTS,]` can be used as `Dept1, Dept2` or as `Dept1`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[MORE_DEPTS,]...` can be used as
 `{nbsp}` (i.e. 0 times), `Dept1`, `Dept1, Dept2` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME t/TIME`, `t/TIME n/NAME` is also acceptable.
====

=== *Project Manager*

[NOTE]
====
This section is meant for Project Managers'. Some of the following commands are exclusive to the Project Manager.
Project Managers have full jurisdriction to view all information and events.
====

==== Viewing help : `help`

Format: `help`

==== Adding an employee : 'add'

Adds an employee to ProManage +
Format/Prompts: +
Enter a command: `add` +
Enter employee details: `n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS dep/DEPARTMENT [t/TAG]...`

Example: +
`add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01 dep/ADMIN`

==== Listing all personnel of the company : 'list'

Shows a list of personnel in the company +
Format/Prompts: +
Enter a command: `list`

==== Editing an employee : 'edit'

Edits the details of the employee: +
Format/Prompts: +
Enter a command: `edit LIST_INDEX n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS dep/DEPARTMENT t/TAG…​`

****
* Edits the event at the specified `INDEX`. The index refers to the index number shown in the displayed event list. The
index *must be a positive integer* 1, 2, 3, ... +
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the person will be removed i.e adding of tags is not cumulative.
* You can remove all the person’s tags by typing t/ without specifying any tags after it.
****

==== Deleting an employee : 'delete'

Delete an employee from ProManage: +
Format/Prompts: +
Enter a command: `delete LIST_INDEX`

==== Adding an event: `addEvent`

Adds an event to ProManage, via a series of prompts +
Format/Prompts: +
Enter a command: `addEvent` +
Enter event details: `n/NAME d/DESCRIPTION l/LOCATION date/DATE(DDMMYY) s/START TIME e/END TIME`  +

Example: +
`addEvent` +
`n/Board Meeting d/Weekly Meeting l/Conference Room 1 date/2018-09-28 s/12:00 e/23:59 ` +
Creates an event named Board Meeting.

==== Listing all events: `schedule`

Display the full list of events in the project. +
Format: `schedule`

==== Invite employees: `invite`

Add employees to the project event at the respective specified INDEX. The index refers to the index number shown in the
displayed person and event list. The index must be a positive integer 1, 2, 3... +
Format: `invite LIST_INDEX to/SCHEDULE_INDEX` +
Example: invite 1 to/2

==== Remove employee: `remove`

Removes an employee from the project event. +
Format/Prompts: `remove SCHEDULE_INDEX  n/NAME` +
Example: remove 10 n/John Doe


==== Modifying an event: `editEvent`

Modifying the event at the specified INDEX. The index refers to the index number shown in the displayed event list. The
index must be a positive integer 1, 2, 3... +
Input nil if it is not the field to be changed. +
Format/Prompts: +
Enter a command: `editEvent SCHEDULE_INDEX` +
Enter event details: `n/NAME d/DESCRIPTION l/LOCATION date/DATE(DDMMYY) s/START TIME e/END TIME`  +

****
* Edits the event at the specified `INDEX`. The index refers to the index number shown in the displayed event list. The
index *must be a positive integer* 1, 2, 3, ... +
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

Examples:
* Enter a command: `editEvent 10`  +
Enter event details: n/Weekly Meeting d/Check on progress l/Conference Room 2 date/2018-09-10 s/12:00 e/14:00`

==== Locating events by name: `find`

Finds the event whose names contain any of the given keywords. +
Format: `find KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `Budget Review` will match `budget review`
* The order of the keywords does not matter. e.g. `Budget Review` will match `Review Budget`
* Only the name is searched.
* Only full words will be matched e.g. `Budget` will not match `Budg`
* Events matching at least one keyword will be returned (i.e. `OR` search). e.g. `Budget Review` will return `Budget`, `Review`
****

Examples:

* `find Budget` +
Returns `Budget Review` and `Budget Press Release`
* `find Budget Review` +
Returns any event having names `Budget` or `Review`

==== Deleting an event : `deleteEvent`

Delete the event at the specified INDEX. +
Format/Prompts: +
Enter a command: `deleteEvent SCHEDULE_INDEX`

****
* Deletes the event at the specified `INDEX`.
* The index refers to the index number shown in the displayed event/task list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `schedule` +
`deleteEvent 2` +
Deletes the 2nd event in the address book.
* `find Meeting` +
`deleteEvent 1` +
Deletes the 1st event in the results of the `find` command.


==== Selecting an event: `select`

Selects the event identified by the index number used in the displayed event list. +
Format/Prompts: +
Enter a command: `select SCHEDULE_INDEX`

****
* Selects the event and loads the full description of the event at the specified `INDEX`.
* The index refers to the index number shown in the displayed event list.
* The index *must be a positive integer* `1, 2, 3, ...`
****

Examples:

* `schedule` +
`select 2` +
Selects the 2nd event in the event schedule.
* `find Meeting` +
`select 1` +
Selects the 1st event in the results of the `find` command.

==== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format/Prompts: +
Enter a command: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

// tag::undoredo[]
==== Undoing previous command : `undo`

Restores the event schedule to the state before the previous _undoable_ command was executed. +
Format/Prompts: +
Enter a command: `undo`

[NOTE]
====
Undoable commands: those commands that modify the event schedule's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `cancel 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `cancel 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

==== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command. +
Format/Prompts: +
Enter a command: `redo`

Examples:

* `cancel 1` +
`undo` (reverses the `cancel 1` command) +
`redo` (reapplies the `cancel 1` command) +

* `cancel 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `cancel 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `cancel 1` command) +
`redo` (reapplies the `cancel 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

==== Clearing all entries : `clear`

Clears all entries from the event schedule. +
Format/Prompts: +
Enter a command: `clear`

==== Exiting the program : `exit`

Exits the program. +
Format/Prompts: +
Enter a command: `exit`

==== Saving the data

ProManage data saves data in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

=== *Department Head*

[NOTE]
====
This section is meant for Department Heads'.
Department Heads can only access his/her own department’s events.
====
//TODO confirm that department heads cannot add people?
==== Viewing help : `help`

Format: `help`

==== Adding an event: `addEvent`

Adds an event to ProManage, via a series of prompts +
Format/Prompts: +
Enter a command: `addEvent` +
Enter event details: `n/NAME d/DESCRIPTION l/LOCATION date/DATE(DDMMYY) s/START TIME e/END TIME`  +

Example: +
`addEvent` +
`n/Board Meeting d/Weekly Meeting l/Conference Room 1 date/2018-09-28 s/12:00 e/23:59 ` +
Creates an event named Board Meeting.

==== Listing all events: `schedule`

Display the full list of events in the project. +
Format: `schedule`

==== Invite employees: `invite`

Add employees to the project event at the respective specified INDEX. The index refers to the index number shown in the
displayed person and event list. The index must be a positive integer 1, 2, 3... +
Format: `invite LIST_INDEX to/SCHEDULE_INDEX` +
Example: invite 1 to/2

==== Remove employee: `remove`

Removes an employee from the project event. +
Format/Prompts: `remove SCHEDULE_INDEX  n/NAME` +
Example: remove 10 n/John Doe


==== Modifying an event: `editEvent`

Modifying the event at the specified INDEX. The index refers to the index number shown in the displayed event list. The
index must be a positive integer 1, 2, 3... +
Input nil if it is not the field to be changed. +
Format/Prompts: +
Enter a command: `editEvent SCHEDULE_INDEX` +
Enter event details: `n/NAME d/DESCRIPTION l/LOCATION date/DATE(DDMMYY) s/START TIME e/END TIME`  +

****
* Edits the event at the specified `INDEX`. The index refers to the index number shown in the displayed event list. The
index *must be a positive integer* 1, 2, 3, ... +
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

Examples:
* Enter a command: `editEvent 10`  +
Enter event details: n/Weekly Meeting d/Check on progress l/Conference Room 2 date/2018-09-10 s/12:00 e/14:00`

==== Locating events by name: `find`

Finds the event whose names contain any of the given keywords. +
Format: `find KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `Budget Review` will match `budget review`
* The order of the keywords does not matter. e.g. `Budget Review` will match `Review Budget`
* Only the name is searched.
* Only full words will be matched e.g. `Budget` will not match `Budg`
* Events matching at least one keyword will be returned (i.e. `OR` search). e.g. `Budget Review` will return `Budget`, `Review`
****

Examples:

* `find Budget` +
Returns `Budget Review` and `Budget Press Release`
* `find Budget Review` +
Returns any event having names `Budget` or `Review`

==== Deleting an event : `deleteEvent`

Delete the event at the specified INDEX. +
Format/Prompts: +
Enter a command: `deleteEvent SCHEDULE_INDEX`

****
* Deletes the event at the specified `INDEX`.
* The index refers to the index number shown in the displayed event/task list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `schedule` +
`deleteEvent 2` +
Deletes the 2nd event in the address book.
* `find Meeting` +
`deleteEvent 1` +
Deletes the 1st event in the results of the `find` command.


==== Selecting an event: `select`

Selects the event identified by the index number used in the displayed event list. +
Format/Prompts: +
Enter a command: `select SCHEDULE_INDEX`

****
* Selects the event and loads the full description of the event at the specified `INDEX`.
* The index refers to the index number shown in the displayed event list.
* The index *must be a positive integer* `1, 2, 3, ...`
****

Examples:

* `schedule` +
`select 2` +
Selects the 2nd event in the event schedule.
* `find Meeting` +
`select 1` +
Selects the 1st event in the results of the `find` command.

==== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format/Prompts: +
Enter a command: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

// tag::undoredo[]
==== Undoing previous command : `undo`

Restores the event schedule to the state before the previous _undoable_ command was executed. +
Format/Prompts: +
Enter a command: `undo`

[NOTE]
====
Undoable commands: those commands that modify the event schedule's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `cancel 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `cancel 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

==== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command. +
Format/Prompts: +
Enter a command: `redo`

Examples:

* `cancel 1` +
`undo` (reverses the `cancel 1` command) +
`redo` (reapplies the `cancel 1` command) +

* `cancel 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `cancel 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `cancel 1` command) +
`redo` (reapplies the `cancel 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

==== Clearing all entries : `clear`

Clears all entries from the event schedule. +
Format/Prompts: +
Enter a command: `clear`

==== Exiting the program : `exit`

Exits the program. +
Format/Prompts: +
Enter a command: `exit`

==== Saving the data

ProManage data saves data in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

=== *Employee*

[NOTE]
====
This section is meant for Employees.
Employees can only access his/her own departments' events.
====

==== Listing all events: `schedule`

Display the full list of events in the project. +
Format/Prompts: `schedule`


==== Requests for a statistics of a week or get a suggested common meeting time by analysing multiple users’ calendars: `query`
Format/Prompts: +
Enter a command: `query'
//TODO Finalise what this section does
Examples:

* `query stats` +
Displays the statistics of a week

* `query meetings` +
Displays a suggested common meeting time


==== Submit a completed task: `submit`

Example:
* `submit 1` +


Task with id 1 is submitted as complete.

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add*: `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS dep/DEPARTMENT [t/TAG]...`

* *List* : `list`

* *Edit* : `edit LIST_INDEX n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS dep/DEPARTMENT t/TAG…​`

* *Delete* : `delete LIST_INDEX`

* *addEvent* : `addEvent n/NAME d/DESCRIPTION l/LOCATION date/DATE s/START TIME e/END TIME ` +
// TODO figure this out! Enter description or instructions: `INSTRUCTIONS`

* *Schedule* : `schedule`

* *Invite* : `invite LIST_INDEX to/SCHEDULE_INDEX`

* *Remove* : `remove SCHEDULE_INDEX  n/NAME`

* *editEvent* : `n/NAME d/DESCRIPTION l/LOCATION date/DATE s/START TIME e/END TIME `

* *Find* : `find KEYWORD [MORE_KEYWORDS]`

* *deleteEvent* : `deleteEvent SCHEDULE_INDEX`

* *Select* : `select SCHEDULE_INDEX`

* *History* : `history`

* *Undo* : `undo`

* *Redo* : `redo`

* *Clear* : `clear`

* *Exit* : `exit`

